/* Modified by NetHackJP contributor @satokiyon; latest change date: 2026-06-06. */
/* NetHack 5.0	jp_data_lookup.c */
/* Japanese aliases for data.base lookup.
 * Keep data.base keys in English and only map player input for lookup.
 */

#include "hack.h"

struct jp_data_lookup_alias {
    const char *jp_key;
    const char *en_key;
};

/* Minimal seed dictionary: keep small and grow based on real misses. */
static const struct jp_data_lookup_alias jp_data_lookup_aliases[] = {
    { "しゅちょう", "?atriarch" },
    { "首長", "?atriarch" },
    { "えーえす", "A.S" },
    { "えーえすいにしゃる", "A.S" },
    { "あぼっと", "abbot" },
    { "修道院長", "abbot" },
    { "師範", "abbot" },
    { "あぼりじに", "aborigine" },
    { "げんじゅうみん", "aborigine" },
    { "原住民", "aborigine" },
    { "えーしー", "ac" },
    { "アーマークラス", "ac" },
    { "防御等級", "ac" },
    { "あしっどぶろぶ", "acid blob" },
    { "酸のぶろっぶ", "acid blob" },
    { "えいくりす", "aclys" },
    { "あこらいと", "acolyte" },
    { "じしゃ", "acolyte" },
    { "侍祭", "acolyte" },
    { "侍者", "acolyte" },
    { "あでぷと", "adept" },
    { "じさい", "adept" },
    { "侍祭", "adept" },
    { "熟達者", "adept" },
    { "あどべんちゃらー", "adventurer" },
    { "ぼうけんしゃ", "adventurer" },
    { "冒険者", "adventurer" },
    { "めのう", "agate" },
    { "瑪瑙", "agate" },
    { "風の精", "air elemental" },
    { "あくりす", "aklys" },
    { "あるけみー", "alchemy" },
    { "錬金術", "alchemy" },
    { "あれあっくす", "aleax" },
    { "あるたー", "altar" },
    { "さいだん", "altar" },
    { "祭壇", "altar" },
    { "あまてらす", "amaterasu omikami" },
    { "あまてらすおおみかみ", "amaterasu omikami" },
    { "天照大神", "amaterasu omikami" },
    { "こはく", "amber" },
    { "琥珀", "amber" },
    { "あむねじあ", "amnesia" },
    { "健忘", "amnesia" },
    { "あもーらす", "amorous demon" },
    { "あもーらすでーもん", "amorous demon" },
    { "好色な悪魔", "amorous demon" },
    { "あみゅれっと", "amulet" },
    { "護符", "amulet" },
    { "あみゅれっとおぶ", "amulet of" },
    { "護符", "amulet of" },
    { "いぇんだーのごふ", "amulet of yendor" },
    { "いぇんだーの護符", "amulet of yendor" },
    { "てんし", "angel" },
    { "天使", "angel" },
    { "あんぐるど", "angled poleaxe" },
    { "あんぐるどぽーるあっくす", "angled poleaxe" },
    { "斜刃の長柄斧", "angled poleaxe" },
    { "あんぐりー", "angry god" },
    { "あんふーる", "anhur" },
    { "あんくもるぽーく", "ankh-morpork" },
    { "あんくもーぽーく", "ankh-morpork" },
    { "あんく・もるぽーく", "ankh-morpork" },
    { "あんしゃる", "anshar" },
    { "あり", "ant" },
    { "あんと", "ant" },
    { "兵隊蟻", "ant" },
    { "巨大蟻", "ant" },
    { "火蟻", "ant" },
    { "蟻", "ant" },
    { "あぬ", "anu" },
    { "えいぷ", "ape" },
    { "類人猿", "ape" },
    { "えいぷらいく", "apelike creature" },
    { "えいぷらいくくりーちゃー", "apelike creature" },
    { "猿人", "apelike creature" },
    { "りんご", "apple" },
    { "林檎", "apple" },
    { "あぷれんてぃす", "apprentice" },
    { "実習生", "apprentice" },
    { "見習い", "apprentice" },
    { "あーばれすたー", "arbalester" },
    { "どへい", "arbalester" },
    { "弩兵", "arbalester" },
    { "石弓兵", "arbalester" },
    { "あるく", "arc" },
    { "主席司祭", "arch priest" },
    { "あーちりっち", "arch-lich" },
    { "あーけおろじ", "archeolog" },
    { "こうこがく", "archeolog" },
    { "あーけおろじすと", "archeologist" },
    { "考古学者", "archeologist" },
    { "あーちゃー", "archer" },
    { "しゃげきしゅ", "archer" },
    { "射手", "archer" },
    { "射撃手", "archer" },
    { "あるこん", "archon" },
    { "執政官", "archon" },
    { "ありおっく", "arioch" },
    { "あーまー", "armor" },
    { "鎧", "armor" },
    { "あーまー", "armour" },
    { "よろい", "armour" },
    { "あろー", "arrow" },
    { "矢", "arrow" },
    { "あーさー", "arthur" },
    { "あーさー王", "arthur" },
    { "あしかが", "ashikaga takauji" },
    { "あしかがたかうじ", "ashikaga takauji" },
    { "足利尊氏", "ashikaga takauji" },
    { "あすもでうす", "asmodeus" },
    { "あすぴらんと", "aspirant" },
    { "しゅうどうしゃ", "aspirant" },
    { "しゅうどうじょ", "aspirant" },
    { "修道女", "aspirant" },
    { "修道者", "aspirant" },
    { "志願者", "aspirant" },
    { "あため", "athame" },
    { "儀式短剣", "athame" },
    { "あてね", "athen" },
    { "あてんだんと", "attendant" },
    { "付き人", "attendant" },
    { "随行員", "attendant" },
    { "おの", "axe" },
    { "斧", "axe" },
    { "あほろーとる", "axolotl" },
    { "べるぜぶぶ", "b*lzebub" },
    { "べるぜぶぶ", "baalzebub" },
    { "黒どらごんの子供", "baby black dragon" },
    { "青どらごんの子供", "baby blue dragon" },
    { "わにの子供", "baby crocodile" },
    { "金色どらごんの子供", "baby gold dragon" },
    { "灰色どらごんの子供", "baby gray dragon" },
    { "緑どらごんの子供", "baby green dragon" },
    { "ろんぐわーむの子供", "baby long worm" },
    { "おれんじどらごんの子供", "baby orange dragon" },
    { "紫わーむの子供", "baby purple worm" },
    { "赤色どらごんの子供", "baby red dragon" },
    { "銀色どらごんの幼体", "baby silver dragon" },
    { "白どらごんの子供", "baby white dragon" },
    { "黄色どらごんの子供", "baby yellow dragon" },
    { "じゅんきし", "bachelor" },
    { "ばちぇらー", "bachelor" },
    { "准騎士", "bachelor" },
    { "学士", "bachelor" },
    { "ばっど", "bad luck" },
    { "ばっどらっく", "bad luck" },
    { "不運", "bad luck" },
    { "かばん", "bag" },
    { "袋", "bag" },
    { "ばるろぐ", "balrog" },
    { "ばるきてりうむ", "baluchitherium" },
    { "ばなな", "banana" },
    { "あっかん", "bandit" },
    { "ばんでぃっと", "bandit" },
    { "山賊", "bandit" },
    { "悪漢", "bandit" },
    { "きしゅきし", "banneret" },
    { "はたてきし", "banneret" },
    { "ばなれっと", "banneret" },
    { "旗手騎士", "banneret" },
    { "旗騎士", "banneret" },
    { "ばんしー", "banshee" },
    { "泣き女", "banshee" },
    { "ばー", "bar" },
    { "酒場", "bar" },
    { "ばーばりあん", "barbarian" },
    { "蛮人", "barbarian" },
    { "野蛮人", "barbarian" },
    { "ばーぶど", "barbed devil" },
    { "ばーぶどでびる", "barbed devil" },
    { "有棘悪魔", "barbed devil" },
    { "棘の悪魔", "barbed devil" },
    { "ばるでぃっしゅ", "bardiche" },
    { "長柄大斧", "bardiche" },
    { "すで", "bare*handed" },
    { "素手", "bare*handed" },
    { "ばろう・わいと", "barrow wight" },
    { "こうもり", "bat" },
    { "ばっと", "bat" },
    { "吸血こうもり", "bat" },
    { "巨大こうもり", "bat" },
    { "蝙蝠", "bat" },
    { "ばっとおあばーど", "bat or bird" },
    { "蝙蝠または鳥", "bat or bird" },
    { "ばとるあっくす", "battle?axe" },
    { "戦斧", "battle?axe" },
    { "くまわな", "bear*trap" },
    { "熊罠", "bear*trap" },
    { "べく", "bec de corbin" },
    { "べくどこるばん", "bec de corbin" },
    { "鴉嘴槍", "bec de corbin" },
    { "はち", "bee" },
    { "びー", "bee" },
    { "女王蜂", "bee" },
    { "殺人蜂", "bee" },
    { "蜂", "bee" },
    { "かぶとむし", "beetle" },
    { "びーとる", "beetle" },
    { "巨大かぶと虫", "beetle" },
    { "甲虫", "beetle" },
    { "べる", "bell" },
    { "鐘", "bell" },
    { "おーぷにんぐのべる", "bell of opening" },
    { "開門の鐘", "bell of opening" },
    { "びるぎざーむ", "bill-guisarme" },
    { "鉤槍斧", "bill-guisarme" },
    { "ぶらっくどらごん", "black dragon" },
    { "黒どらごん", "black dragon" },
    { "黒い光", "black light" },
    { "黒なーが", "black naga" },
    { "黒なーがの雛", "black naga hatchling" },
    { "黒ぷりん", "black pudding" },
    { "黒ゆにこーん", "black unicorn" },
    { "ぶらいんどいお", "blind io" },
    { "盲目のいお", "blind io" },
    { "ぶらいんど", "blindfold" },
    { "めかくし", "blindfold" },
    { "目隠し", "blindfold" },
    { "ぶろぶ", "blob" },
    { "粘塊", "blob" },
    { "ぶるーどらごん", "blue dragon" },
    { "青どらごん", "blue dragon" },
    { "あおいじぇりー", "blue jelly" },
    { "あおいろじぇりー", "blue jelly" },
    { "あおいろぜりー", "blue jelly" },
    { "ぶるー", "blue jelly" },
    { "ぶるーじぇりー", "blue jelly" },
    { "青いじぇりー", "blue jelly" },
    { "青いぜりー", "blue jelly" },
    { "青色じぇりー", "blue jelly" },
    { "青色ぜりー", "blue jelly" },
    { "ぼーん", "bone devil" },
    { "ぼーんでびる", "bone devil" },
    { "骨の悪魔", "bone devil" },
    { "ぶっく", "book" },
    { "でっどのしょ", "book of the dead" },
    { "死者の書", "book of the dead" },
    { "ぶーめらん", "boomerang" },
    { "ぶーつ", "boot" },
    { "ぶーず", "booze" },
    { "酒", "booze" },
    { "きょせき", "boulder" },
    { "巨石", "boulder" },
    { "ぼう", "bow" },
    { "弓", "bow" },
    { "ぶらんち", "branch stair" },
    { "さんぞく", "brigand" },
    { "ぶりがんど", "brigand" },
    { "山賊", "brigand" },
    { "追い剥ぎ", "brigand" },
    { "ぶりじっと", "brigit" },
    { "ぶろーど", "broad" },
    { "ぶろーどぴっく", "broad pick" },
    { "幅広つるはし", "broad pick" },
    { "ぶろーどそーど", "broadsword" },
    { "幅広剣", "broadsword" },
    { "茶色もーるど", "brown mold" },
    { "茶色ぷりん", "brown pudding" },
    { "ばぐべあ", "bugbear" },
    { "ばぐべあー", "bugbear" },
    { "らっぱ", "bugle" },
    { "喇叭", "bugle" },
    { "むち", "bullwhip" },
    { "牛追い鞭", "bullwhip" },
    { "あきす", "burglar" },
    { "ばーぐらー", "burglar" },
    { "泥棒", "burglar" },
    { "空巣", "burglar" },
    { "けーれーしょん", "c?ration" },
    { "配給食", "c?ration" },
    { "かまくすとり", "camaxtli" },
    { "かましゅとり", "camaxtli" },
    { "かめろっと", "camelot" },
    { "きゃめろっと城", "camelot" },
    { "きゃんどらぶらむ", "candelabrum" },
    { "燭台", "candelabrum" },
    { "きゃんでぃでいと", "candidate" },
    { "にゅうもんきぼうしゃ", "candidate" },
    { "候補者", "candidate" },
    { "入門希望者", "candidate" },
    { "きゃんどる", "candle" },
    { "蝋燭", "candle" },
    { "きゃんでぃ", "candy bar" },
    { "きゃんでぃばー", "candy bar" },
    { "いぬ科", "canine" },
    { "けいないん", "canine" },
    { "けないん", "canine" },
    { "犬類", "canine" },
    { "かのん", "canon" },
    { "せいじゃ", "canon" },
    { "教会法", "canon" },
    { "聖者", "canon" },
    { "せいじょ", "canoness" },
    { "聖女", "canoness" },
    { "きゃぷてん", "captain" },
    { "指揮官", "captain" },
    { "隊長", "captain" },
    { "人喰い猿", "carnivorous ape" },
    { "にんじん", "carrot" },
    { "人参", "carrot" },
    { "きゃっと", "cat" },
    { "ねこ", "cat" },
    { "大きな猫", "cat" },
    { "家猫", "cat" },
    { "小猫", "cat" },
    { "猫", "cat" },
    { "けいゔ", "cave" },
    { "けいぶどうぇらー", "cave dweller" },
    { "洞窟の住人", "cave dweller" },
    { "洞窟ぐも", "cave spider" },
    { "かゔ", "cave*man" },
    { "けいゔまん", "cave*man" },
    { "どうくつにん", "cave*man" },
    { "洞窟", "cave*man" },
    { "洞窟人", "cave*man" },
    { "けいぶまん", "caveman" },
    { "洞窟人", "caveman" },
    { "けいぶうーまん", "cavewoman" },
    { "洞窟女", "cavewoman" },
    { "けんたうろす", "centaur" },
    { "せんたうる", "centaur" },
    { "半人半馬", "centaur" },
    { "山のけんたうろす", "centaur" },
    { "森のけんたうろす", "centaur" },
    { "草原のけんたうろす", "centaur" },
    { "むかで", "centipede" },
    { "百足", "centipede" },
    { "けるべろす", "cerberus" },
    { "地獄の番犬", "cerberus" },
    { "かめれおん", "chameleon" },
    { "変色蜥蜴", "chameleon" },
    { "ちゃんぴおん", "champion" },
    { "まほうつかい", "champion" },
    { "ゆうしゃ", "champion" },
    { "勇者", "champion" },
    { "英雄", "champion" },
    { "魔法使い", "champion" },
    { "ちゃーじ", "charge card" },
    { "ちゃーじかーど", "charge card" },
    { "かろん", "charo*n" },
    { "たからばこ", "chest" },
    { "宝箱", "chest" },
    { "こういきし", "chevalier" },
    { "しゅゔぁりえ", "chevalier" },
    { "騎士", "chevalier" },
    { "高位騎士", "chevalier" },
    { "こういおんなきし", "chevaliere" },
    { "高位女騎士", "chevaliere" },
    { "ちかとりす", "chickatrice" },
    { "しゅりょう", "chieftain" },
    { "しーふてん", "chieftain" },
    { "ちーふてん", "chieftain" },
    { "族長", "chieftain" },
    { "首領", "chieftain" },
    { "ちーさんらいつー", "chih*sung*tzu" },
    { "ちーそんつー", "chih*sung*tzu" },
    { "かいほうい", "chirurgeon" },
    { "げかい", "chirurgeon" },
    { "外科医", "chirurgeon" },
    { "くろまてぃっく", "chromatic dragon" },
    { "くろまてぃっくどらごん", "chromatic dragon" },
    { "くろまてぃっく・どらごん", "chromatic dragon" },
    { "虹色竜", "chromatic dragon" },
    { "しとりん", "citrine" },
    { "黄水晶", "citrine" },
    { "くれい", "clay golem" },
    { "くれいごーれむ", "clay golem" },
    { "くれーごーれむ", "clay golem" },
    { "土のごーれむ", "clay golem" },
    { "粘土のごーれむ", "clay golem" },
    { "くりーばー", "cleaver" },
    { "肉切り包丁", "cleaver" },
    { "くれりっく", "cleric" },
    { "僧侶", "cleric" },
    { "聖職者", "cleric" },
    { "くろーく", "cloak" },
    { "まんと", "cloak" },
    { "うん", "cloud" },
    { "くも", "cloud" },
    { "くらうど", "cloud" },
    { "雲", "cloud" },
    { "くらぶ", "club" },
    { "棍棒", "club" },
    { "こぶら", "cobra" },
    { "眼鏡蛇", "cobra" },
    { "こかとりす", "cockatrice" },
    { "こいん", "coin" },
    { "硬貨", "coin" },
    { "金貨", "coin" },
    { "こいんず", "coins" },
    { "小銭", "coins" },
    { "金貨", "coins" },
    { "これくたー", "collector" },
    { "しゅうしゅうか", "collector" },
    { "収集家", "collector" },
    { "こんばっと", "combat" },
    { "戦闘", "combat" },
    { "こにかる", "conical hat" },
    { "こにかるはっと", "conical hat" },
    { "円錐帽", "conical hat" },
    { "こんじゅらー", "conjurer" },
    { "呪術師", "conjurer" },
    { "こんかー", "conquer" },
    { "征服", "conquer" },
    { "せいふくしゃ", "conqueror" },
    { "征服者", "conqueror" },
    { "こーぷ", "cope" },
    { "典礼用まんと", "cope" },
    { "こるぬこぴあ", "cornucopia" },
    { "豊穣の角", "cornucopia" },
    { "こるぬたうむ", "cornuthaum" },
    { "こうあとる", "couatl" },
    { "羽毛蛇", "couatl" },
    { "こよーて", "coyote" },
    { "くらむ", "cram" },
    { "詰め込み", "cram" },
    { "非常食", "cram" },
    { "くりーむ", "cream pie" },
    { "くりーむぱい", "cream pie" },
    { "生くりーむぱい", "cream pie" },
    { "くれじっと", "credit card" },
    { "くれじっとかーど", "credit card" },
    { "信用かーど", "credit card" },
    { "くれおそーと", "creosote" },
    { "くろこだいる", "crocodile" },
    { "わに", "crocodile" },
    { "鰐", "crocodile" },
    { "くろいそす", "croesus" },
    { "くろえそす", "croesus" },
    { "くろむ", "crom" },
    { "くろすぼう", "crossbow" },
    { "くりすないふ", "crysknife" },
    { "水晶の短刀", "crysknife" },
    { "くりすたる", "crystal" },
    { "すいしょうだま", "crystal ball" },
    { "水晶玉", "crystal ball" },
    { "くりすたるへるめっと", "crystal helmet" },
    { "水晶の兜", "crystal helmet" },
    { "きゅれーと", "curate" },
    { "じょにんしさい", "curate" },
    { "助任司祭", "curate" },
    { "かんちょう", "curator" },
    { "きゅれーたー", "curator" },
    { "学芸員", "curator" },
    { "館長", "curator" },
    { "かーす", "curse" },
    { "呪い", "curse" },
    { "かっとぱーす", "cutpurse" },
    { "きんちゃくきり", "cutpurse" },
    { "ひったくり", "cutpurse" },
    { "くうん", "cwn*n" },
    { "くんあぬん", "cwn*n" },
    { "きゅくろぷす", "cyclops" },
    { "さいくろぷす", "cyclops" },
    { "一つ目巨人", "cyclops" },
    { "だがー", "dagger" },
    { "短剣", "dagger" },
    { "こしもと", "daimyo" },
    { "だいみょう", "daimyo" },
    { "大名", "daimyo" },
    { "腰元", "daimyo" },
    { "おんなきしちょう", "dame" },
    { "でいむ", "dame" },
    { "女騎士", "dame" },
    { "女騎士長", "dame" },
    { "だーく", "dark one" },
    { "だーくわん", "dark one" },
    { "暗きもの", "dark one" },
    { "闇の者", "dark one" },
    { "だーと", "dart" },
    { "投げ矢", "dart" },
    { "です", "death" },
    { "死神", "death" },
    { "でるふぃ", "delphi" },
    { "でるぽい", "delphi" },
    { "でみりっち", "demilich" },
    { "でもごるごん", "demogorgon" },
    { "でーもん", "demon" },
    { "悪魔", "demon" },
    { "でーもんべいん", "demonbane" },
    { "悪魔殺し", "demonbane" },
    { "でんてっど", "dented pot" },
    { "へこみなべ", "dented pot" },
    { "凹んだ鍋", "dented pot" },
    { "だいやもんど", "diamond" },
    { "金剛石", "diamond" },
    { "こういん", "digger" },
    { "でぃがー", "digger" },
    { "掘削者", "digger" },
    { "穴掘り", "digger" },
    { "鉱員", "digger" },
    { "でぃりしうむ", "dilithium" },
    { "でぃんご", "dingo" },
    { "野犬", "dingo" },
    { "でぃすくわーるど", "discworld novel" },
    { "でぃすえんちゃんたー", "disenchanter" },
    { "吸魔の怪物", "disenchanter" },
    { "魔力吸い", "disenchanter" },
    { "でぃすぱてる", "dispater" },
    { "でぃすぺいたー", "dispater" },
    { "でぃすぺーた", "dispater" },
    { "でぃすぷれいさー", "displacer beast" },
    { "でぃすぷれいさーびーすと", "displacer beast" },
    { "位相獣", "displacer beast" },
    { "じん", "djinn" },
    { "でぃじん", "djinn" },
    { "精霊", "djinn" },
    { "魔神", "djinn" },
    { "いしゃ", "doctor" },
    { "医師", "doctor" },
    { "医者", "doctor" },
    { "いぬ", "dog" },
    { "どっぐ", "dog" },
    { "へるはうんど", "dog" },
    { "犬", "dog" },
    { "かいたとびら", "door" },
    { "とじたとびら", "door" },
    { "とびら", "door" },
    { "どあ", "door" },
    { "もん", "door" },
    { "扉", "door" },
    { "閉じた扉", "door" },
    { "開いた扉", "door" },
    { "いりぐち", "doorway" },
    { "とぐち", "doorway" },
    { "入口", "doorway" },
    { "出入口", "doorway" },
    { "戸口", "doorway" },
    { "どっぺるげんがー", "doppelganger" },
    { "変身怪物", "doppelganger" },
    { "だぶるへっどあっくす", "double?headed?axe" },
    { "両頭斧", "double?headed?axe" },
    { "おれんじどらごん", "dragon" },
    { "おれんじどらごんの子供", "dragon" },
    { "どらごん", "dragon" },
    { "りゅう", "dragon" },
    { "竜", "dragon" },
    { "龍", "dragon" },
    { "どらごんすけーる", "dragon*scale" },
    { "竜鱗", "dragon*scale" },
    { "どらごんべいん", "dragonbane" },
    { "竜殺し", "dragonbane" },
    { "そうしょうしょちし", "dresser" },
    { "どれっさー", "dresser" },
    { "創傷処置師", "dresser" },
    { "化粧箪笥", "dresser" },
    { "どらむ", "drum" },
    { "太鼓", "drum" },
    { "だんす", "dunce" },
    { "劣等生", "dunce" },
    { "愚者", "dunce" },
    { "だんじょん", "dungeon" },
    { "迷宮", "dungeon" },
    { "ほこりの渦", "dust vortex" },
    { "どわー", "dwar" },
    { "どわー", "dwarf" },
    { "どわーふ", "dwarf" },
    { "どわーふのぞんび", "dwarf" },
    { "どわーふのみいら", "dwarf" },
    { "どわーふの支配者", "dwarf" },
    { "どわーふの首領", "dwarf" },
    { "どわーふのおう", "dwarf king" },
    { "どわーふの王", "dwarf king" },
    { "ドワーフの王", "dwarf king" },
    { "どわーふのきぞく", "dwarf lord" },
    { "どわーふの貴族", "dwarf lord" },
    { "ドワーフの貴族", "dwarf lord" },
    { "どわーふのみいら", "dwarf mummy" },
    { "どわーふのぞんび", "dwarf zombie" },
    { "どわーふの根", "dwarven root" },
    { "どわーゔぇんるーと", "dwarven root" },
    { "どわーゔん", "dwarven root" },
    { "えあれんでぃる", "earendil" },
    { "土の精", "earth elemental" },
    { "いーる", "eel" },
    { "鰻", "eel" },
    { "たまご", "egg" },
    { "卵", "egg" },
    { "えるべれす", "elbereth" },
    { "えれくとりっく", "electric eel" },
    { "でんきうなぎ", "electric eel" },
    { "電気うなぎ", "electric eel" },
    { "電気鰻", "electric eel" },
    { "えれめんたる", "elemental" },
    { "精霊", "elemental" },
    { "えるふ", "elf" },
    { "えるふのぞんび", "elf" },
    { "えるふのみいら", "elf" },
    { "えるふの君主", "elf" },
    { "えるふの貴族", "elf" },
    { "森のえるふ", "elf" },
    { "灰色えるふ", "elf" },
    { "緑えるふ", "elf" },
    { "えるふのみいら", "elf mummy" },
    { "えるふのぞんび", "elf zombie" },
    { "えるゔん", "elven" },
    { "えるふの外套", "elven cloak" },
    { "えるゔんくろーく", "elven cloak" },
    { "えるふの君主", "elven monarch" },
    { "えるゔんもなーく", "elven monarch" },
    { "えるふ王", "elvenking" },
    { "えるゔんきんぐ", "elvenking" },
    { "えるふ女王", "elvenqueen" },
    { "えるゔんくいーん", "elvenqueen" },
    { "えるうぃんぐ", "elwing" },
    { "いたいしょりし", "embalmer" },
    { "えんばーまー", "embalmer" },
    { "遺体処理師", "embalmer" },
    { "遺体防腐師", "embalmer" },
    { "えめらるど", "emerald" },
    { "翠玉", "emerald" },
    { "えんぴりっく", "empiric" },
    { "ちりょうし", "empiric" },
    { "治療師", "empiric" },
    { "経験医", "empiric" },
    { "えんちゃんたー", "enchanter" },
    { "付呪師", "enchanter" },
    { "えんちゃんとれす", "enchantress" },
    { "女付呪師", "enchantress" },
    { "えねるぎーの渦", "energy vortex" },
    { "えんぐれいゔ", "engrav" },
    { "彫刻", "engrav" },
    { "えぴだうろす", "epidaurus" },
    { "えりにゅえす", "erinyes" },
    { "復讐女神", "erinyes" },
    { "いりにす", "erinys" },
    { "えりにす", "erinys" },
    { "復讐の女神", "erinys" },
    { "えすくわいあ", "esquire" },
    { "じゅうし", "esquire" },
    { "従士", "esquire" },
    { "えってぃん", "ettin" },
    { "えてぃん", "ettin" },
    { "えてぃんのぞんび", "ettin" },
    { "えてぃんのみいら", "ettin" },
    { "双頭巨人", "ettin" },
    { "えてぃんのみいら", "ettin mummy" },
    { "えてぃんのぞんび", "ettin zombie" },
    { "えゔぉーかー", "evoker" },
    { "喚起者", "evoker" },
    { "えくすかりばー", "excalibur" },
    { "えくすかべーたー", "excavator" },
    { "くっさくしゃ", "excavator" },
    { "掘削者", "excavator" },
    { "発掘者", "excavator" },
    { "えくすかーしょにすと", "excursionist" },
    { "しゅうゆうりょこうしゃ", "excursionist" },
    { "周遊旅行者", "excursionist" },
    { "遠足家", "excursionist" },
    { "えくすひゅーまー", "exhumer" },
    { "はっくつしゃ", "exhumer" },
    { "掘り起こし人", "exhumer" },
    { "発掘者", "exhumer" },
    { "えくすぺんしぶかめら", "expensive camera" },
    { "こうかなかめら", "expensive camera" },
    { "高価なかめら", "expensive camera" },
    { "えくすぷろーらー", "explorer" },
    { "たんけんか", "explorer" },
    { "探検家", "explorer" },
    { "あい", "eye" },
    { "さまよう目", "eye" },
    { "えちおぴかのめ", "eye of the aethiopica" },
    { "えちおぴかの目", "eye of the aethiopica" },
    { "あいず", "eyes of the overworld" },
    { "おーばーわーるどのめ", "eyes of the overworld" },
    { "おーばーわーるどの目", "eyes of the overworld" },
    { "異界の眼", "eyes of the overworld" },
    { "ふぁみん", "famine" },
    { "ふぇみん", "famine" },
    { "飢饉", "famine" },
    { "ふぉーしゃーる", "fauchard" },
    { "長柄鎌槍", "fauchard" },
    { "ふぇどら", "fedora" },
    { "中折れ帽", "fedora" },
    { "ねこ科", "feline" },
    { "ふぃーらいん", "feline" },
    { "ふぇらいん", "feline" },
    { "猫科", "feline" },
    { "ふぃーるど", "field worker" },
    { "ふぃーるどわーかー", "field worker" },
    { "ろうどうしゃ", "field worker" },
    { "労働者", "field worker" },
    { "野良仕事人", "field worker" },
    { "ふぁいと", "fight" },
    { "戦い", "fight" },
    { "うらないし", "fighter" },
    { "せんし", "fighter" },
    { "とうしおとめ", "fighter" },
    { "占い師", "fighter" },
    { "戦士", "fighter" },
    { "闘士", "fighter" },
    { "闘士乙女", "fighter" },
    { "ふぃぎゅありん", "figurine" },
    { "ふぃぎゅりん", "figurine" },
    { "小像", "figurine" },
    { "どろぼう", "filcher" },
    { "ふぃるちゃー", "filcher" },
    { "掏摸", "filcher" },
    { "泥棒", "filcher" },
    { "ふぁいあ", "fire" },
    { "ふぁいああんと", "fire ant" },
    { "ふぁいあーあんと", "fire ant" },
    { "火蟻", "fire ant" },
    { "火の精", "fire elemental" },
    { "炎の巨人", "fire giant" },
    { "ひのわな", "fire trap" },
    { "火の罠", "fire trap" },
    { "火炎の罠", "fire trap" },
    { "炎の渦", "fire vortex" },
    { "ふれいる", "flail" },
    { "連接棍", "flail" },
    { "ふれっしゅ", "flesh golem" },
    { "ふれっしゅごーれむ", "flesh golem" },
    { "肉のごーれむ", "flesh golem" },
    { "肉塊ごーれむ", "flesh golem" },
    { "ふりんと", "flint" },
    { "火打石", "flint" },
    { "さまよう目", "floating eye" },
    { "ふゆうするめだま", "floating eye" },
    { "ふろーてぃんぐ", "floating eye" },
    { "浮遊する目玉", "floating eye" },
    { "浮遊する眼", "floating eye" },
    { "ふるーと", "flute" },
    { "横笛", "flute" },
    { "笛", "flute" },
    { "ふぉぐ", "fog cloud" },
    { "霧", "fog cloud" },
    { "霧の雲", "fog cloud" },
    { "ふーど", "food" },
    { "食物", "food" },
    { "おいはぎ", "footpad" },
    { "すり", "footpad" },
    { "ふっとぱっど", "footpad" },
    { "追いはぎ", "footpad" },
    { "森のけんたうろす", "forest centaur" },
    { "ふぉーちゅん", "fortune cookie" },
    { "ふぉーちゅんくっきー", "fortune cookie" },
    { "辻占煎餅", "fortune cookie" },
    { "いずみ", "fountain" },
    { "せんすい", "fountain" },
    { "ふんすい", "fountain" },
    { "噴水", "fountain" },
    { "泉", "fountain" },
    { "きつね", "fox" },
    { "狐", "fox" },
    { "ふれいかす", "fracas" },
    { "乱闘", "fracas" },
    { "氷の球体", "freezing sphere" },
    { "ふろんど", "frond" },
    { "葉", "frond" },
    { "吹雪の巨人", "frost giant" },
    { "ふろーずん", "frozen" },
    { "ふるーつ", "fruit" },
    { "果物", "fruit" },
    { "ふるーつなまえ", "fruitname" },
    { "果物名", "fruitname" },
    { "ふぁんぐ", "fung" },
    { "紫きのこ", "fung" },
    { "菌類", "fung" },
    { "ふゅーりーず", "furies" },
    { "復讐の女神たち", "furies" },
    { "がらんと", "gallant" },
    { "きしみならい", "gallant" },
    { "勇士", "gallant" },
    { "騎士見習い", "gallant" },
    { "がーごいる", "gargoyle" },
    { "石像怪物", "gargoyle" },
    { "がーりっく", "garlic" },
    { "にんにく", "garlic" },
    { "大蒜", "garlic" },
    { "小さなへび", "garter snake" },
    { "包子がす", "gas spore" },
    { "がんとれっと", "gauntlets" },
    { "ごーんとれっと", "gauntlets" },
    { "籠手", "gauntlets" },
    { "げっこー", "gecko" },
    { "やもり", "gecko" },
    { "げへな", "gehenn" },
    { "げへんな", "gehenn" },
    { "地獄", "gehenn" },
    { "地獄界", "gehenn" },
    { "ぜらちなす", "gelatinous cube" },
    { "ぜらちなすきゅーぶ", "gelatinous cube" },
    { "ぜらちんきゅーぶ", "gelatinous cube" },
    { "ぜりー状立方体", "gelatinous cube" },
    { "じぇむ", "gem" },
    { "宝石", "gem" },
    { "じぇむおあろっく", "gem or rock" },
    { "宝石か石", "gem or rock" },
    { "じぇねてぃっく", "genetic engineer" },
    { "じぇねてぃっくえんじにあ", "genetic engineer" },
    { "遺伝子工学者", "genetic engineer" },
    { "げりゅおん", "geryon" },
    { "げーりゅおーん", "geryon" },
    { "ごーすと", "ghost" },
    { "ゆうれい", "ghost" },
    { "幽霊", "ghost" },
    { "ぐーる", "ghoul" },
    { "食屍鬼", "ghoul" },
    { "じゃいあんと", "giant" },
    { "巨人", "giant" },
    { "じゃいあんとあんと", "giant ant" },
    { "巨大蟻", "giant ant" },
    { "巨大こうもり", "giant bat" },
    { "じゃいあんとびーとる", "giant beetle" },
    { "巨大かぶと虫", "giant beetle" },
    { "じゃいあんといーる", "giant eel" },
    { "大鰻", "giant eel" },
    { "巨大うなぎ", "giant eel" },
    { "じゃいあんとひゅーまのいど", "giant humanoid" },
    { "巨人人型生物", "giant humanoid" },
    { "巨大なみみっく", "giant mimic" },
    { "巨人のみいら", "giant mummy" },
    { "巨大ねずみ", "giant rat" },
    { "巨大ぐも", "giant spider" },
    { "巨人のぞんび", "giant zombie" },
    { "ぐれいぶ", "glaive" },
    { "長刀", "glaive" },
    { "がらすごーれむ", "glass golem" },
    { "がらすのごーれむ", "glass golem" },
    { "がらす喰い", "glass piercer" },
    { "ぐろるかむ", "glorkum" },
    { "ぐろーかむ", "glorkum" },
    { "ぐろーぶ", "gloves" },
    { "手甲", "gloves" },
    { "手袋", "gloves" },
    { "のーむ", "gnom" },
    { "ぐのむ", "gnome" },
    { "こびと", "gnome" },
    { "のーむ", "gnome" },
    { "のーむのぞんび", "gnome" },
    { "のーむのみいら", "gnome" },
    { "のーむの支配者", "gnome" },
    { "のーむの首領", "gnome" },
    { "のーむの魔法使い", "gnome" },
    { "侏儒", "gnome" },
    { "小人", "gnome" },
    { "のーむのおう", "gnome king" },
    { "のーむの王", "gnome king" },
    { "ノームの王", "gnome king" },
    { "のーむのきぞく", "gnome lord" },
    { "のーむの貴族", "gnome lord" },
    { "ノームの貴族", "gnome lord" },
    { "のーむのみいら", "gnome mummy" },
    { "のーむのぞんび", "gnome zombie" },
    { "のーみっしゅ", "gnomish" },
    { "のーみっしゅまいんず", "gnomish mines" },
    { "のーむ鉱山", "gnomish mines" },
    { "のーみっしゅうぃざーど", "gnomish wizard" },
    { "のーむの魔法使い", "gnomish wizard" },
    { "ごぶりん", "goblin" },
    { "小鬼", "goblin" },
    { "ごぶりんきんぐ", "goblin king" },
    { "ごぶりん王", "goblin king" },
    { "ごっど", "god" },
    { "神", "god" },
    { "ごっです", "goddess" },
    { "女神", "goddess" },
    { "ごーるど", "gold" },
    { "黄金", "gold" },
    { "金色どらごん", "gold dragon" },
    { "ごーるどごーれむ", "gold golem" },
    { "金のごーれむ", "gold golem" },
    { "黄金ごーれむ", "gold golem" },
    { "ごーるどぴーす", "gold piece" },
    { "金色なーが", "golden naga" },
    { "金色なーがの雛", "golden naga hatchling" },
    { "がらすのごーれむ", "golem" },
    { "ごれむ", "golem" },
    { "ごーれむ", "golem" },
    { "ぐらんど", "grand master" },
    { "ぐらんどますたー", "grand master" },
    { "大師範", "grand master" },
    { "総師範", "grand master" },
    { "はか", "grave" },
    { "墓", "grave" },
    { "墓石", "grave" },
    { "ぐれいどらごん", "gray dragon" },
    { "灰色どらごん", "gray dragon" },
    { "灰色うーず", "gray ooze" },
    { "灰色ゆにこーん", "gray unicorn" },
    { "ぐれいすわんでぃあ", "grayswandir" },
    { "ぐれいすわんでぃる", "grayswandir" },
    { "あぶら", "grease" },
    { "ぐりーす", "grease" },
    { "ゆし", "grease" },
    { "油", "grease" },
    { "油脂", "grease" },
    { "ぐりーんどらごん", "green dragon" },
    { "緑どらごん", "green dragon" },
    { "緑もーるど", "green mold" },
    { "緑すらいむ", "green slime" },
    { "緑えるふ", "green-elf" },
    { "ぐれむりん", "gremlin" },
    { "小悪鬼", "gremlin" },
    { "灰色えるふ", "grey-elf" },
    { "ぐりっど", "grid bug" },
    { "ぐりっどばぐ", "grid bug" },
    { "格子虫", "grid bug" },
    { "がーど", "guard" },
    { "番兵", "guard" },
    { "衛兵", "guard" },
    { "番兵なーが", "guardian naga" },
    { "番兵なーがの雛", "guardian naga hatchling" },
    { "がいど", "guide" },
    { "案内人", "guide" },
    { "ぎざーむ", "guisarme" },
    { "ぐにょき", "gunyoki" },
    { "はんのむ", "h?nnom" },
    { "はち", "hachi" },
    { "はちこう", "hachi" },
    { "はるばーど", "halberd" },
    { "戟", "halberd" },
    { "はるしねいと", "hallucinat" },
    { "幻覚", "hallucinat" },
    { "はーぷ", "harp" },
    { "竪琴", "harp" },
    { "はたもと", "hatamoto" },
    { "旗本", "hatamoto" },
    { "はわいあんしゃつ", "hawaiian*shirt" },
    { "花柄しゃつ", "hawaiian*shirt" },
    { "ひーらー", "healer" },
    { "治療", "healer" },
    { "治療師", "healer" },
    { "あーりまんのしんぞう", "heart of ahriman" },
    { "あーりまんの心臓", "heart of ahriman" },
    { "はーと", "heart of ahriman" },
    { "じごく", "hell" },
    { "地獄", "hell" },
    { "へるはうんど", "hell hound" },
    { "へるはうんどの仔", "hell hound pup" },
    { "へるむ", "helm" },
    { "兜", "helm" },
    { "こうきのかぶと", "helm of brilliance" },
    { "高輝の兜", "helm of brilliance" },
    { "けいかいのかぶと", "helm of caution" },
    { "警戒の兜", "helm of caution" },
    { "たいりつせいれつのかぶと", "helm of opposite alignment" },
    { "対立属性の兜", "helm of opposite alignment" },
    { "てれぱしーのかぶと", "helm of telepathy" },
    { "てれぱしーの兜", "helm of telepathy" },
    { "へるめっと", "helmet" },
    { "兜", "helmet" },
    { "はーばりすと", "herbalist" },
    { "やくそうちりょうし", "herbalist" },
    { "薬草師", "herbalist" },
    { "薬草治療師", "herbalist" },
    { "へるめす", "hermes" },
    { "えいゆう", "hero" },
    { "ひーろー", "hero" },
    { "まじゅつし", "hero" },
    { "勇者", "hero" },
    { "英雄", "hero" },
    { "魔術師", "hero" },
    { "じょえいゆう", "heroine" },
    { "ひろいん", "heroine" },
    { "女英雄", "heroine" },
    { "へずろう", "hezrou" },
    { "はい", "high" },
    { "だいそうじょう", "high priest" },
    { "大僧上", "high priest" },
    { "丘の巨人", "hill giant" },
    { "丘のおーく", "hill orc" },
    { "ひぽくらてす", "hippocrates" },
    { "ほびっと", "hobbit" },
    { "ほぶごぶりん", "hobgoblin" },
    { "大鬼", "hobgoblin" },
    { "せいすい", "holy water" },
    { "ほーりー", "holy water" },
    { "聖水", "holy water" },
    { "ほむんくるす", "hom*nculus" },
    { "人造小人", "hom*nculus" },
    { "小人造生物", "hom*nculus" },
    { "ふーでっど", "hooded cloak" },
    { "ふーでっどくろーく", "hooded cloak" },
    { "頭巾付き外套", "hooded cloak" },
    { "ふっく", "hook" },
    { "鉤", "hook" },
    { "ほるん", "horn" },
    { "角笛", "horn" },
    { "ほーんおぶぷれんてぃ", "horn of plenty" },
    { "豊穣の角笛", "horn of plenty" },
    { "ほーんど", "horned devil" },
    { "ほーんどでびる", "horned devil" },
    { "角ある悪魔", "horned devil" },
    { "角のある悪魔", "horned devil" },
    { "うま", "horse" },
    { "ほーす", "horse" },
    { "戦闘用の馬", "horse" },
    { "馬", "horse" },
    { "ほーすまん", "horsem" },
    { "騎馬兵", "horsem" },
    { "家猫", "housecat" },
    { "ふえととる", "hu*h*eto*l" },
    { "ふへととる", "hu*h*eto*l" },
    { "ふへととるの使い", "hu*h*eto*l" },
    { "火の神", "hu*h*eto*l" },
    { "ふぁんてぃ", "huan*ti" },
    { "ふあんてぃ", "huan*ti" },
    { "蛇人族", "huan*ti" },
    { "おおきなにくのかたまり", "huge chunk of meat" },
    { "ひゅーじ", "huge chunk of meat" },
    { "巨大な肉塊", "huge chunk of meat" },
    { "あんばーはるく", "hulk" },
    { "はるく", "hulk" },
    { "巨躯", "hulk" },
    { "ひゅーまん", "human" },
    { "人間", "human" },
    { "人間のぞんび", "human" },
    { "人間のみいら", "human" },
    { "人間のみいら", "human mummy" },
    { "人間のぞんび", "human zombie" },
    { "ひゅーまのいど", "humanoid" },
    { "人型生物", "humanoid" },
    { "はんがー", "hunger" },
    { "空腹", "hunger" },
    { "はんたー", "hunter" },
    { "狩人", "hunter" },
    { "あいす", "ice" },
    { "ひょう", "ice" },
    { "氷", "ice" },
    { "あいすぼっくす", "ice box" },
    { "氷室", "ice box" },
    { "あいすでびる", "ice devil" },
    { "氷の悪魔", "ice devil" },
    { "氷のとろる", "ice troll" },
    { "氷の渦", "ice vortex" },
    { "いでふぃくす", "idefix" },
    { "いぐあな", "iguana" },
    { "いんぷ", "imp" },
    { "小悪魔", "imp" },
    { "いんぷまたはかきゅうあくま", "imp or minor demon" },
    { "いんぷまたは下級悪魔", "imp or minor demon" },
    { "いんきゅばす", "incubus" },
    { "淫魔", "incubus" },
    { "いにしえいと", "initiate" },
    { "しゅぎょうそう", "initiate" },
    { "修行僧", "initiate" },
    { "初学者", "initiate" },
    { "いんせくと", "insect" },
    { "昆虫", "insect" },
    { "いんせくつ", "insects" },
    { "昆虫群", "insects" },
    { "昆虫類", "insects" },
    { "いんゔぇすてぃげいたー", "investigator" },
    { "ちょうさしゃ", "investigator" },
    { "調査員", "investigator" },
    { "調査者", "investigator" },
    { "あいあん", "iron" },
    { "鉄製", "iron" },
    { "あいあんぼーる", "iron ball" },
    { "てっきゅう", "iron ball" },
    { "鉄球", "iron ball" },
    { "てっこうし", "iron bars" },
    { "てっごうし", "iron bars" },
    { "てつこうし", "iron bars" },
    { "てつごうし", "iron bars" },
    { "鉄こうし", "iron bars" },
    { "鉄ごうし", "iron bars" },
    { "鉄格子", "iron bars" },
    { "あいあんちぇいん", "iron chain" },
    { "てっさ", "iron chain" },
    { "鉄鎖", "iron chain" },
    { "あいろんごーれむ", "iron golem" },
    { "鉄のごーれむ", "iron golem" },
    { "鉄喰い", "iron piercer" },
    { "いしゅたる", "ishtar" },
    { "いっせき", "issek" },
    { "いくそす", "ixoth" },
    { "いずちゃっく", "izchak" },
    { "じゃばうぉっく", "jabberwock" },
    { "じゃしんす", "jacinth" },
    { "風信子石", "jacinth" },
    { "じゃっくぶーつ", "jack*boot" },
    { "じゃっかる", "jackal" },
    { "山犬", "jackal" },
    { "じゃど", "jade" },
    { "ひすい", "jade" },
    { "翡翠", "jade" },
    { "じゃがー", "jaguar" },
    { "美洲豹", "jaguar" },
    { "じゃべりん", "javelin" },
    { "投げ槍", "javelin" },
    { "くらげ", "jellyfish" },
    { "じぇりーふぃっしゅ", "jellyfish" },
    { "海月", "jellyfish" },
    { "じょうしゅ", "joshu" },
    { "じょしゅ", "joshu" },
    { "城主", "joshu" },
    { "じゃーにやー", "journeyer" },
    { "たびびと", "journeyer" },
    { "旅人", "journeyer" },
    { "じゅーぶれっくす", "jubilex" },
    { "じゅーいぶれっくす", "juiblex" },
    { "じょうびれっくす", "juiblex" },
    { "けーれーしょん", "k?ration" },
    { "配給食", "k?ration" },
    { "かぶと", "kabuto" },
    { "かたな", "katana" },
    { "刀", "katana" },
    { "けるぷ", "kelp" },
    { "昆布", "kelp" },
    { "海藻", "kelp" },
    { "けるべろすしすてむ", "kerberos" },
    { "警備員", "keystone kop" },
    { "きりん", "ki-rin" },
    { "麒麟", "ki-rin" },
    { "きらーびー", "killer bee" },
    { "殺人蜂", "killer bee" },
    { "きんぐ", "king" },
    { "あーさー王", "king arthur" },
    { "きんぐあーさー", "king arthur" },
    { "こねこ", "kitten" },
    { "子猫", "kitten" },
    { "小猫", "kitten" },
    { "ないふ", "knife" },
    { "小刀", "knife" },
    { "おんなきし", "knight" },
    { "きし", "knight" },
    { "ないと", "knight" },
    { "女騎士", "knight" },
    { "騎士", "knight" },
    { "こぼると", "kobold" },
    { "こぼるど", "kobold" },
    { "こぼるどの首領", "kobold" },
    { "こぼるとのきぞく", "kobold lord" },
    { "こぼるとの貴族", "kobold lord" },
    { "こぼるとろーど", "kobold lord" },
    { "こぼるどのきぞく", "kobold lord" },
    { "こぼるどの貴族", "kobold lord" },
    { "こぼるどろーど", "kobold lord" },
    { "こぼるとのみいら", "kobold mummy" },
    { "こぼるとみいら", "kobold mummy" },
    { "こぼるどのみいら", "kobold mummy" },
    { "こぼるどみいら", "kobold mummy" },
    { "こぼるとのじゅじゅつし", "kobold shaman" },
    { "こぼるとの呪術師", "kobold shaman" },
    { "こぼるどのじゅじゅつし", "kobold shaman" },
    { "こぼるどの呪術師", "kobold shaman" },
    { "こぼるとぞんび", "kobold zombie" },
    { "こぼるとのぞんび", "kobold zombie" },
    { "こぼるどぞんび", "kobold zombie" },
    { "こぼるどのぞんび", "kobold zombie" },
    { "こくしゅ", "kokushu" },
    { "りょうしゅ", "kokushu" },
    { "領主", "kokushu" },
    { "こっぷ", "kop" },
    { "警吏", "kop" },
    { "警部補", "kop kaptain" },
    { "巡査部長", "kop lieutenant" },
    { "巡査", "kop sergeant" },
    { "こす", "kos" },
    { "こと", "koto" },
    { "箏", "koto" },
    { "くらーけん", "kraken" },
    { "海魔", "kraken" },
    { "くろいそす", "kroisos" },
    { "くげ", "kuge" },
    { "ろうじゅう", "kuge" },
    { "公家", "kuge" },
    { "老中", "kuge" },
    { "くのいち", "kunoichi" },
    { "くの一", "kunoichi" },
    { "女忍者", "kunoichi" },
    { "たてのひめゆうしゃ", "lady" },
    { "れでぃ", "lady" },
    { "淑女", "lady" },
    { "盾の姫勇者", "lady" },
    { "れでぃらっく", "lady luck" },
    { "幸運の女神", "lady luck" },
    { "しきょう", "lama" },
    { "らま", "lama" },
    { "司教", "lama" },
    { "らんぷ", "lamp" },
    { "らんす", "lance" },
    { "騎槍", "lance" },
    { "らんど", "land" },
    { "らんどまいん", "land mine" },
    { "地雷", "land mine" },
    { "らんたん", "lantern" },
    { "提灯", "lantern" },
    { "らーじ", "large" },
    { "らーじぼっくす", "large box" },
    { "大箱", "large box" },
    { "大きな猫", "large cat" },
    { "大きな犬", "large dog" },
    { "おおきなこぼると", "large kobold" },
    { "おおきなこぼるど", "large kobold" },
    { "大きなこぼると", "large kobold" },
    { "大きなこぼるど", "large kobold" },
    { "大きなみみっく", "large mimic" },
    { "らーじろっく", "large rock" },
    { "大岩", "large rock" },
    { "らーゔぁ", "larvae" },
    { "幼虫", "larvae" },
    { "ようがん", "lava" },
    { "らば", "lava" },
    { "らゔぁ", "lava" },
    { "溶岩", "lava" },
    { "りーしゅ", "leash" },
    { "引き綱", "leash" },
    { "かわよろい", "leather armor" },
    { "れざー", "leather armor" },
    { "れざーあーまー", "leather armor" },
    { "革製", "leather armor" },
    { "革鎧", "leather armor" },
    { "れざーごーれむ", "leather golem" },
    { "皮のごーれむ", "leather golem" },
    { "れんばす", "lembas" },
    { "れんばすぱん", "lembas" },
    { "れみゅあ", "lemure" },
    { "れむれーす", "lemure" },
    { "れおくろった", "leocrotta" },
    { "れぷらこーん", "leprechaun" },
    { "小妖精", "leprechaun" },
    { "れうくろった", "leu*otta" },
    { "れるおくろった", "leu*otta" },
    { "怪獣れうくろった", "leu*otta" },
    { "あーちりっち", "lich" },
    { "でみりっち", "lich" },
    { "りっち", "lich" },
    { "死霊術師", "lich" },
    { "らいけん", "lichen" },
    { "地衣類", "lichen" },
    { "苔の怪物", "lichen" },
    { "るてなんと", "lieutenant" },
    { "副官", "lieutenant" },
    { "らいと", "light" },
    { "光", "light" },
    { "灯り", "light" },
    { "黄色い光", "light" },
    { "黒い光", "light" },
    { "仔犬", "little dog" },
    { "とかげ", "lizard" },
    { "りざーど", "lizard" },
    { "蜥蜴", "lizard" },
    { "ろき", "loki" },
    { "ろんぐ", "long" },
    { "ろんぐぽーるあっくす", "long poleaxe" },
    { "長柄の斧", "long poleaxe" },
    { "ろんぐわーむ", "long worm" },
    { "ながいわーむのしっぽ", "long worm tail" },
    { "ろんぐわーむの尻尾", "long worm tail" },
    { "長いわーむの尻尾", "long worm tail" },
    { "でぃあなのちょうきゅう", "longbow of diana" },
    { "でぃあなの長弓", "longbow of diana" },
    { "ろんぐぼう", "longbow of diana" },
    { "ろんぐぼうおぶだいあな", "longbow of diana" },
    { "長弓", "longbow of diana" },
    { "るっきんぐ", "looking" },
    { "るっきんぐぐらす", "looking glass" },
    { "姿見", "looking glass" },
    { "みはり", "lookout" },
    { "るっくあうと", "lookout" },
    { "見張り", "lookout" },
    { "かーなぼん卿", "lord" },
    { "たてのゆうしゃ", "lord" },
    { "だいまほうつかい", "lord" },
    { "ろーど", "lord" },
    { "君主", "lord" },
    { "大魔法使い", "lord" },
    { "盾の勇者", "lord" },
    { "かーなぼん卿", "lord carnarvon" },
    { "かーなーゔぉん卿", "lord carnarvon" },
    { "ろーどかーなーう゛ぉん", "lord carnarvon" },
    { "ろーどさとう", "lord sato" },
    { "佐藤卿", "lord sato" },
    { "大名佐藤", "lord sato" },
    { "支配者すると", "lord surtur" },
    { "るっつぇるん", "lucern" },
    { "るっつぇるんはんまー", "lucern hammer" },
    { "槍頭槌", "lucern hammer" },
    { "らっく", "luck" },
    { "幸運", "luck" },
    { "るぐ", "lug" },
    { "るーぐ", "lug" },
    { "光神", "lug" },
    { "らーかー", "lurker" },
    { "るーかー", "lurker" },
    { "潜み", "lurker" },
    { "らーかー", "lurker above" },
    { "らいかんするーぷ", "lycanthrope" },
    { "人狼類", "lycanthrope" },
    { "りんくす", "lynx" },
    { "山猫", "lynx" },
    { "まなんなん", "ma*annan" },
    { "海神", "ma*annan" },
    { "めいす", "mace" },
    { "鎚矛", "mace" },
    { "めいじ", "mage" },
    { "魔術師", "mage" },
    { "まじっく", "magic" },
    { "まじっくまーかー", "magic marker" },
    { "魔法のまーかー", "magic marker" },
    { "まーりんのみらー", "magic mirror of merlin" },
    { "まーりんの魔法の鏡", "magic mirror of merlin" },
    { "まーりんの魔鏡", "magic mirror of merlin" },
    { "まじっくべいん", "magicbane" },
    { "まじしゃん", "magician" },
    { "奇術師", "magician" },
    { "ちりょうたいし", "magister" },
    { "まぎすたー", "magister" },
    { "教授", "magister" },
    { "治療大師", "magister" },
    { "まぎすとら", "magistra" },
    { "女教授", "magistra" },
    { "まぐずまん", "mags*man" },
    { "まーくすまん", "mags*man" },
    { "射手", "mags*man" },
    { "ごうとう", "magsman" },
    { "強盗", "magsman" },
    { "めいる", "mail" },
    { "鎖かたびら", "mail" },
    { "鎖帷子", "mail" },
    { "めいるでーもん", "mail daemon" },
    { "めじゃー", "major" },
    { "めじゃーでーもん", "major demon" },
    { "上級悪魔", "major demon" },
    { "ぶそうおとめ", "man-at-arms" },
    { "まんあっとあーむず", "man-at-arms" },
    { "れいかんし", "man-at-arms" },
    { "兵士", "man-at-arms" },
    { "武装乙女", "man-at-arms" },
    { "重装兵", "man-at-arms" },
    { "霊感師", "man-at-arms" },
    { "まねす", "manes" },
    { "亡霊", "manes" },
    { "まるどぅく", "marduk" },
    { "まりりす", "marilith" },
    { "まーくすまん", "marks*man" },
    { "狙撃手", "marks*man" },
    { "めいしゃしゅ", "marksman" },
    { "名射手", "marksman" },
    { "まるす", "mars" },
    { "まーず", "mars" },
    { "まーしゃる", "martial" },
    { "まーしゃるあーつ", "martial arts" },
    { "武術", "martial arts" },
    { "かえん", "master" },
    { "ますたー", "master" },
    { "めんきょかいでん", "master" },
    { "免許皆伝", "master" },
    { "達人", "master" },
    { "ますたーあさしん", "master assassin" },
    { "暗殺者の頭領", "master assassin" },
    { "暗殺術師範", "master assassin" },
    { "かえん", "master kaen" },
    { "けいん師範", "master kaen" },
    { "ますたーけいん", "master kaen" },
    { "とうぞくぎるどのますたーきー", "master key of thievery" },
    { "盗賊術のますたーきー", "master key of thievery" },
    { "盗賊術の万能鍵", "master key of thievery" },
    { "ますたーりっち", "master lich" },
    { "ますたーまいんどふれあ", "master mind flayer" },
    { "ますたーおぶしーぶず", "master of thieves" },
    { "盗賊の頭領", "master of thieves" },
    { "盗賊頭", "master of thieves" },
    { "ますとどん", "mastodon" },
    { "つるはし", "mattock" },
    { "まとっく", "mattock" },
    { "もーど", "maud" },
    { "にく", "meat" },
    { "みーと", "meat" },
    { "肉", "meat" },
    { "めでぃっく", "medic" },
    { "めでぃっく", "medic* ossium" },
    { "衛生兵", "medic* ossium" },
    { "せいこつい", "medicus ossium" },
    { "整骨医", "medicus ossium" },
    { "めでゅーさ", "medusa" },
    { "めれー", "melee" },
    { "近接戦", "melee" },
    { "めろん", "melon" },
    { "まーきゅりー", "mercury" },
    { "まいくろすこーぷ", "microscope" },
    { "顕微鏡", "microscope" },
    { "みみっく", "mimic" },
    { "擬態怪物", "mimic" },
    { "まいんど", "mind flayer" },
    { "まいんどふれあ", "mind flayer" },
    { "まいんどふれいやー", "mind flayer" },
    { "精神", "mind flayer" },
    { "精神喰い", "mind flayer" },
    { "まいん", "mine" },
    { "採掘", "mine" },
    { "みにおん", "minion" },
    { "ふえととるのしもべ", "minion of huhetotl" },
    { "ふえととるの眷属", "minion of huhetotl" },
    { "ふへととるの使い", "minion of huhetotl" },
    { "みのたうろす", "minotaur" },
    { "みらー", "mirror" },
    { "鏡", "mirror" },
    { "みとら", "mit*ra" },
    { "みとら神", "mit*ra" },
    { "みすりる", "mithril" },
    { "しんせいのそうぼう", "mitre of holiness" },
    { "まいたー", "mitre of holiness" },
    { "まいたーおぶほーりねす", "mitre of holiness" },
    { "冠帽", "mitre of holiness" },
    { "神聖の僧帽", "mitre of holiness" },
    { "聖性の冠帽", "mitre of holiness" },
    { "みょるにる", "mjollnir" },
    { "もぐ", "mog" },
    { "もーぐ", "mog" },
    { "もいすと", "moist" },
    { "しめったたおる", "moist towel" },
    { "湿ったたおる", "moist towel" },
    { "もろっく", "mol?ch" },
    { "もーろっく", "mol?ch" },
    { "邪神", "mol?ch" },
    { "かび", "mold" },
    { "もーるど", "mold" },
    { "緑もーるど", "mold" },
    { "茶色もーるど", "mold" },
    { "赤色もーるど", "mold" },
    { "黄色もーるど", "mold" },
    { "もん", "mon" },
    { "もんく", "monk" },
    { "修行僧", "monk" },
    { "僧", "monk" },
    { "武闘家", "monk" },
    { "もんきー", "monkey" },
    { "猿", "monkey" },
    { "もるどーるのおーく", "mordor orc" },
    { "もーにんぐ", "morning" },
    { "もーにんぐすたー", "morning star" },
    { "鉄球棍", "morning star" },
    { "山のけんたうろす", "mountain centaur" },
    { "やまのにんふ", "mountain nymph" },
    { "山のにんふ", "mountain nymph" },
    { "じゅう", "mumak" },
    { "むまく", "mumak" },
    { "むーまく", "mumak" },
    { "まみー", "mummy" },
    { "みいら", "mummy" },
    { "木乃伊", "mummy" },
    { "まみーらっぴんぐ", "mummy wrapping" },
    { "みいらの包帯", "mummy wrapping" },
    { "なが", "naga" },
    { "なーが", "naga" },
    { "なぎなた", "naginata" },
    { "薙刀", "naginata" },
    { "ないあど", "naiad" },
    { "水の精", "naiad" },
    { "なじゃ", "naja" },
    { "なるふぇしに", "nalfeshnee" },
    { "なるふぇしゅにー", "nalfeshnee" },
    { "なるぞく", "nalzok" },
    { "なるぞっく", "nalzok" },
    { "なるぞっくの神殿", "nalzok" },
    { "なずぐる", "nazgul" },
    { "ねあんでるたーる", "neanderthal" },
    { "ねあんでるたーる人", "neanderthal" },
    { "旧人", "neanderthal" },
    { "ねくろまんさー", "necromancer" },
    { "ねふぇれと", "neferet" },
    { "みどりのねふぇれと", "neferet the green" },
    { "緑のねふぇれと", "neferet the green" },
    { "いもり", "newt" },
    { "にゅーと", "newt" },
    { "にんじゃ", "ninja" },
    { "忍者", "ninja" },
    { "にんじゃとう", "ninja-to" },
    { "忍者刀", "ninja-to" },
    { "のまど", "nomad" },
    { "ゆうぼくみん", "nomad" },
    { "遊牧民", "nomad" },
    { "のるん", "norn" },
    { "のゔぇる", "novel" },
    { "小説", "novel" },
    { "しょしんしゅぎょうしゃ", "novice" },
    { "のゔぃす", "novice" },
    { "初心修行者", "novice" },
    { "初心者", "novice" },
    { "ぬんちゃく", "nunchaku" },
    { "なーす", "nurse" },
    { "看護婦", "nurse" },
    { "看護師", "nurse" },
    { "にんふ", "nymph" },
    { "妖精", "nymph" },
    { "おぶしでぃあん", "obsidian" },
    { "黒曜石", "obsidian" },
    { "おーかー", "ochre" },
    { "おうどいろじぇりー", "ochre jelly" },
    { "おうどいろぜりー", "ochre jelly" },
    { "おーかーじぇりー", "ochre jelly" },
    { "黄土色じぇりー", "ochre jelly" },
    { "黄土色ぜりー", "ochre jelly" },
    { "黄土色のじぇりー", "ochre jelly" },
    { "黄土色のぜりー", "ochre jelly" },
    { "おーでぃん", "odin" },
    { "おふぁー", "offer" },
    { "供え物", "offer" },
    { "おふらー", "offler" },
    { "おーが", "ogre" },
    { "おーがの暴君", "ogre" },
    { "おーがの首領", "ogre" },
    { "おーがー", "ogre" },
    { "鬼人", "ogre" },
    { "おいるすきん", "oilskin" },
    { "おいるすきんくろーく", "oilskin cloak" },
    { "油布の外套", "oilskin cloak" },
    { "おいるすきんさっく", "oilskin sack" },
    { "油布の袋", "oilskin sack" },
    { "おろぐはい", "olog-hai" },
    { "うーず", "ooze" },
    { "粘液", "ooze" },
    { "軟泥", "ooze" },
    { "おらくる", "oracle" },
    { "神託者", "oracle" },
    { "賢者", "oracle" },
    { "おれんじ", "orange" },
    { "橙", "orange" },
    { "おれんじどらごん", "orange dragon" },
    { "おーぶ", "orb" },
    { "宝珠", "orb" },
    { "おーぶおぶでぃてくしょん", "orb of detection" },
    { "たんちのおーぶ", "orb of detection" },
    { "探知のおーぶ", "orb of detection" },
    { "探知の宝珠", "orb of detection" },
    { "うんめいのおーぶ", "orb of fate" },
    { "おーぶおぶふぇいと", "orb of fate" },
    { "運命のおーぶ", "orb of fate" },
    { "運命の宝珠", "orb of fate" },
    { "おるく", "orc" },
    { "おーく", "orc" },
    { "おーくのぞんび", "orc" },
    { "おーくのみいら", "orc" },
    { "おーくの呪術師", "orc" },
    { "おーくの隊長", "orc" },
    { "おーく族", "orc" },
    { "もるどーるのおーく", "orc" },
    { "丘のおーく", "orc" },
    { "おーくのみいら", "orc mummy" },
    { "おーくの呪術師", "orc shaman" },
    { "おーくのぞんび", "orc zombie" },
    { "おーくのしゅりょう", "orc-captain" },
    { "おーくの隊長", "orc-captain" },
    { "おーくの首領", "orc-captain" },
    { "オークの首領", "orc-captain" },
    { "おるくりすと", "orcrist" },
    { "おるかす", "orcus" },
    { "おーかす", "orcus" },
    { "おーけす", "orcus" },
    { "おりおん", "orion" },
    { "おりおんの野営地", "orion" },
    { "勇者おりおん", "orion" },
    { "おさく", "osaku" },
    { "あうるべあ", "owlbear" },
    { "おうるべあ", "owlbear" },
    { "ぴゅてぃあ", "p*thia" },
    { "巫女", "p*thia" },
    { "ぱどる", "paddle" },
    { "ぱどるさぼてん", "paddle cactus" },
    { "団扇さぼてん", "paddle cactus" },
    { "ぺいじ", "page" },
    { "小姓", "page" },
    { "せいきし", "paladin" },
    { "ぱらでぃん", "paladin" },
    { "聖騎士", "paladin" },
    { "ぱっりうむ", "pall" },
    { "ぱる", "pall" },
    { "法衣", "pall" },
    { "ぱんさー", "panther" },
    { "黒豹", "panther" },
    { "ぺーぱー", "paper" },
    { "紙", "paper" },
    { "ぺーぱーごーれむ", "paper golem" },
    { "紙のごーれむ", "paper golem" },
    { "ぺーぱーばっく", "paperback" },
    { "ぺーぱーばっくぶっく", "paperback book" },
    { "ぺーぱーばっく本", "paperback book" },
    { "ぱーてぃざん", "partisan" },
    { "長柄突槍", "partisan" },
    { "だいしきょう", "patriarch" },
    { "大司教", "patriarch" },
    { "ぺあ", "pear" },
    { "梨", "pear" },
    { "ぺりあす", "pelias" },
    { "ぺれぐりねいと", "peregrinat" },
    { "ぺれぐりねーと", "peregrinat" },
    { "巡礼", "peregrinat" },
    { "へんれきしゃ", "peregrinator" },
    { "遍歴者", "peregrinator" },
    { "ぺるせうす", "perseus" },
    { "ぺすてぃれんす", "pestilence" },
    { "疫病", "pestilence" },
    { "ちりょうい", "physician" },
    { "ふぃじしゃん", "physician" },
    { "内科医", "physician" },
    { "治療医", "physician" },
    { "つるはし", "pick*ax" },
    { "ぴっくあっくす", "pick*ax" },
    { "ぴあさー", "piercer" },
    { "ぴあーさー", "piercer" },
    { "刺突怪", "piercer" },
    { "穿孔魔", "piercer" },
    { "ごろつき", "pilferer" },
    { "ぴるふぁらー", "pilferer" },
    { "窃盗者", "pilferer" },
    { "ぴれじゃー", "pillager" },
    { "りゃくだつしゃ", "pillager" },
    { "略奪者", "pillager" },
    { "せんくしゃ", "pioneer" },
    { "ぱいおにあ", "pioneer" },
    { "先駆者", "pioneer" },
    { "開拓者", "pioneer" },
    { "ぴらにあ", "piranha" },
    { "ぴっと", "pit" },
    { "落とし穴", "pit" },
    { "ぴっとふぃーんど", "pit fiend" },
    { "奈落の悪魔", "pit fiend" },
    { "穴の悪霊", "pit fiend" },
    { "はぶ", "pit viper" },
    { "ぴっとゔぁいぱー", "pit viper" },
    { "穴蝮", "pit viper" },
    { "ぷらちな", "platinum" },
    { "ぷれいすたいる", "play style" },
    { "ぷれいやー", "player" },
    { "ぷらんだー", "plunder?" },
    { "略奪", "plunder?" },
    { "らんぼうもの", "plunderer" },
    { "乱暴者", "plunderer" },
    { "ぽいずん", "poison" },
    { "毒", "poison" },
    { "ぽいずんど", "poisoned" },
    { "毒化", "poisoned" },
    { "ぽーる", "pole" },
    { "ぽーるくりーばー", "pole cleaver" },
    { "長柄肉切り包丁", "pole cleaver" },
    { "ぽーるしっくる", "pole sickle" },
    { "長柄鎌", "pole sickle" },
    { "ぽーるあーむ", "polearm" },
    { "長柄武器", "polearm" },
    { "ぽりもーふ", "polymorph" },
    { "ぽりもーふとらっぷ", "polymorph trap" },
    { "変身の罠", "polymorph trap" },
    { "ぽにー", "pony" },
    { "仔馬", "pony" },
    { "小馬", "pony" },
    { "げーと", "portal" },
    { "ぽーたる", "portal" },
    { "門", "portal" },
    { "ぽせいどん", "poseido*n" },
    { "ぽーしょん", "potion" },
    { "薬", "potion" },
    { "げんかくのくすり", "potion of hallucination" },
    { "幻覚の薬", "potion of hallucination" },
    { "びょうきのくすり", "potion of sickness" },
    { "病気の薬", "potion of sickness" },
    { "すいみんのくすり", "potion of sleeping" },
    { "睡眠の薬", "potion of sleeping" },
    { "ぷれい", "pray" },
    { "祈り", "pray" },
    { "そうりょ", "priest" },
    { "ぷり", "priest" },
    { "ぷりーすと", "priest" },
    { "僧侶", "priest" },
    { "司祭", "priest" },
    { "聖職者", "priest" },
    { "にそう", "priestess" },
    { "尼僧", "priestess" },
    { "ぷりずなー", "prisoner" },
    { "囚人", "prisoner" },
    { "ぷたは", "ptah" },
    { "ぷでぃんぐ", "pudding" },
    { "ぷりん", "pudding" },
    { "ぱにっしゅ", "punish" },
    { "処罰", "punish" },
    { "ぱっぷ", "pup" },
    { "仔犬", "pup" },
    { "ぱーぷる", "purple worm" },
    { "ぱーぷるわーむ", "purple worm" },
    { "紫", "purple worm" },
    { "紫のわーむ", "purple worm" },
    { "紫わーむ", "purple worm" },
    { "ぱいろりすく", "pyrolisk" },
    { "ぴろりすく", "pyrolisk" },
    { "にしきへび", "python" },
    { "ぱいそん", "python" },
    { "大蛇", "python" },
    { "くあどるぺっど", "quadruped" },
    { "四足獣", "quadruped" },
    { "くぁんたむ", "quantum" },
    { "くぁんたむめかにっく", "quantum mechanic" },
    { "量子整備士", "quantum mechanic" },
    { "量子物理学者", "quantum mechanic" },
    { "くあしと", "quasit" },
    { "くあじっと", "quasit" },
    { "くぇいしっと", "quasit" },
    { "くいーんびー", "queen bee" },
    { "女王蜂", "queen bee" },
    { "くえすと", "quest" },
    { "探索", "quest" },
    { "けつぁるこあとる", "quetzalcoatl" },
    { "くいっと", "quit" },
    { "終了", "quit" },
    { "くぃばりんぐぶろぶ", "quivering blob" },
    { "くぃゔぁりんぐぶろぶ", "quivering blob" },
    { "震えるぶろっぶ", "quivering blob" },
    { "兇暴ねずみ", "rabid rat" },
    { "らいでん", "raiden" },
    { "雷電", "raiden" },
    { "しんりゃくしゃ", "raider" },
    { "れいだー", "raider" },
    { "侵略者", "raider" },
    { "襲撃者", "raider" },
    { "らいじん", "raijin" },
    { "雷神", "raijin" },
    { "ぷーこ", "rambler" },
    { "ぷーたろう", "rambler" },
    { "ぷー太郎", "rambler" },
    { "ぷー子", "rambler" },
    { "らんぶらー", "rambler" },
    { "放浪者", "rambler" },
    { "らん", "ran" },
    { "れーんじゃー", "ran" },
    { "れんじゃー", "ranger" },
    { "野伏", "ranger" },
    { "らんさー", "ranseur" },
    { "鉤突槍", "ranseur" },
    { "どぶねずみ", "rat" },
    { "ねずみ", "rat" },
    { "らっと", "rat" },
    { "兇暴ねずみ", "rat" },
    { "巨大ねずみ", "rat" },
    { "鼠", "rat" },
    { "おおがらす", "raven" },
    { "れいゔん", "raven" },
    { "大鴉", "raven" },
    { "ごうとう", "reaver" },
    { "りーゔぁー", "reaver" },
    { "強盗", "reaver" },
    { "略奪戦士", "reaver" },
    { "りこないたー", "reconnoiter" },
    { "偵察", "reconnoiter" },
    { "ていさつ", "reconnoiterer" },
    { "偵察", "reconnoiterer" },
    { "れっどどらごん", "red dragon" },
    { "赤色どらごん", "red dragon" },
    { "赤色もーるど", "red mold" },
    { "赤色なーが", "red naga" },
    { "赤色なーがの雛", "red naga hatchling" },
    { "ねほりにん", "rhizotomist" },
    { "ねほりびと", "rhizotomist" },
    { "りぞとみすと", "rhizotomist" },
    { "根切り師", "rhizotomist" },
    { "根堀人", "rhizotomist" },
    { "らいだー", "rider" },
    { "騎乗者", "rider" },
    { "りんぐ", "ring" },
    { "指輪", "ring" },
    { "りんぐおぶ", "ring of" },
    { "指輪", "ring of" },
    { "いんびじびりてぃのゆびわ", "ring of invisibility" },
    { "透明化の指輪", "ring of invisibility" },
    { "ほうゆうしゃ", "roamer" },
    { "ろーまー", "roamer" },
    { "放遊者", "roamer" },
    { "流浪者", "roamer" },
    { "こそどろ", "robber" },
    { "ろばー", "robber" },
    { "強盗", "robber" },
    { "ろーぶ", "robe" },
    { "法衣", "robe" },
    { "ろっく", "rock" },
    { "岩", "rock" },
    { "ろっくもーる", "rock mole" },
    { "岩もぐら", "rock mole" },
    { "岩喰い", "rock piercer" },
    { "岩のとろる", "rock troll" },
    { "ろーでんと", "rodent" },
    { "齧歯類", "rodent" },
    { "ろーぐ", "rog" },
    { "すり", "rogue" },
    { "ろーぐ", "rogue" },
    { "盗賊", "rogue" },
    { "ろうにん", "ronin" },
    { "ろーにん", "ronin" },
    { "浪人", "ronin" },
    { "るーと", "root" },
    { "根株", "root" },
    { "ろーぷごーれむ", "rope golem" },
    { "紐のごーれむ", "rope golem" },
    { "ろうし", "roshi" },
    { "浪士", "roshi" },
    { "老師", "roshi" },
    { "ろぜ", "rothe" },
    { "ろーす", "rothe" },
    { "ろーず", "rothe" },
    { "さすらい犬", "rover" },
    { "ひょうはくみん", "rover" },
    { "ろーゔぁー", "rover" },
    { "漂泊民", "rover" },
    { "ろーやる", "royal jelly" },
    { "ろーやるぜりー", "royal jelly" },
    { "王乳", "royal jelly" },
    { "王家", "royal jelly" },
    { "ごむほーす", "rubber hose" },
    { "らばーほーす", "rubber hose" },
    { "るびー", "ruby" },
    { "紅玉", "ruby" },
    { "らすともんすたー", "rust monster" },
    { "錆の怪物", "rust monster" },
    { "錆喰い", "rust monster" },
    { "りょうしゅ", "ryoshu" },
    { "老中", "ryoshu" },
    { "領主", "ryoshu" },
    { "すだがー", "s*d*g*r" },
    { "さーべる", "saber" },
    { "せーばー", "saber" },
    { "さーぶる", "sabre" },
    { "さっく", "sack" },
    { "袋物", "sack" },
    { "さくりふぁいす", "sacrific" },
    { "生贄", "sacrific" },
    { "さどる", "saddle" },
    { "鞍", "saddle" },
    { "さけ", "sake" },
    { "日本酒", "sake" },
    { "さらまんだー", "salamander" },
    { "さむ", "sam" },
    { "さむらい", "samurai" },
    { "侍", "samurai" },
    { "武士", "samurai" },
    { "さんですてぃん", "sandestin" },
    { "さふぁいあ", "sapphire" },
    { "青玉", "sapphire" },
    { "さすかっち", "sasquatch" },
    { "さすくわっち", "sasquatch" },
    { "すかるぺる", "scalpel" },
    { "手術刀", "scalpel" },
    { "せぷたー", "sceptre" },
    { "王笏", "sceptre" },
    { "せぷたー", "sceptre of might" },
    { "ちからのおうしゃく", "sceptre of might" },
    { "力の王笏", "sceptre of might" },
    { "しみたー", "scimitar" },
    { "湾刀", "scimitar" },
    { "さそり", "scorpio" },
    { "すこーぴお", "scorpio" },
    { "蠍", "scorpio" },
    { "さそり", "scorpion" },
    { "すこーぴうす", "scorpius" },
    { "大蠍", "scorpius" },
    { "すかうと", "scout" },
    { "せっこう", "scout" },
    { "斥候", "scout" },
    { "すくろーる", "scroll" },
    { "巻物", "scroll" },
    { "ばつのまきもの", "scroll of punishment" },
    { "罰の巻物", "scroll of punishment" },
    { "きしちょう", "seignieur" },
    { "せにょーる", "seignieur" },
    { "貴顕", "seignieur" },
    { "騎士長", "seignieur" },
    { "かきゅうきし", "sergeant" },
    { "さーじゃんと", "sergeant" },
    { "下士官", "sergeant" },
    { "下級騎士", "sergeant" },
    { "軍曹", "sergeant" },
    { "さーぺんと", "serpent" },
    { "大蛇類", "serpent" },
    { "せと", "set" },
    { "せす", "seth" },
    { "どぶねずみ", "sewer rat" },
    { "しゃど", "shad" },
    { "影", "shade" },
    { "しゃどー", "shadow" },
    { "影", "shadow" },
    { "しゃーまんかーるのふ", "shaman karnov" },
    { "しゃーまん・かるのふ", "shaman karnov" },
    { "呪術師かるのふ", "shaman karnov" },
    { "しゃんらいちん", "shan*lai*ching" },
    { "山来清", "shan*lai*ching" },
    { "さめ", "shark" },
    { "しゃーく", "shark" },
    { "鮫", "shark" },
    { "しゃーぷしゅーたー", "sharpshooter" },
    { "じゅくれんしゃしゅ", "sharpshooter" },
    { "熟練射手", "sharpshooter" },
    { "狙撃手", "sharpshooter" },
    { "しーるど", "shield" },
    { "盾", "shield" },
    { "はんしゃのたて", "shield of reflection" },
    { "反射の盾", "shield of reflection" },
    { "しと", "shito" },
    { "使徒", "shito" },
    { "電撃の球体", "shocking sphere" },
    { "しゅーず", "shoes" },
    { "靴", "shoes" },
    { "しょうぐん", "shogun" },
    { "みだいどころ", "shogun" },
    { "将軍", "shogun" },
    { "御台所", "shogun" },
    { "しょっぷきーぱー", "shopkeeper" },
    { "店主", "shopkeeper" },
    { "しゅりーかー", "shrieker" },
    { "絶叫茸", "shrieker" },
    { "しゅりけん", "shuriken" },
    { "手裏剣", "shuriken" },
    { "かんこうきゃく", "sightseer" },
    { "さいとしーあー", "sightseer" },
    { "物見遊山客", "sightseer" },
    { "観光客", "sightseer" },
    { "しるばーどらごん", "silver dragon" },
    { "銀色どらごん", "silver dragon" },
    { "しりうす", "sirius" },
    { "すけるとん", "skeleton" },
    { "骸骨", "skeleton" },
    { "きじゅつし", "skirmisher" },
    { "さんぺいおとめ", "skirmisher" },
    { "すかーみっしゃー", "skirmisher" },
    { "奇術師", "skirmisher" },
    { "散兵", "skirmisher" },
    { "散兵乙女", "skirmisher" },
    { "すらっしゃー", "slasher" },
    { "斬り裂き魔", "slasher" },
    { "さつりくしゃ", "slayer" },
    { "すれいやー", "slayer" },
    { "殺戮者", "slayer" },
    { "すりーぷ", "sleep" },
    { "睡眠", "sleep" },
    { "すらいむ", "slime" },
    { "粘泥", "slime" },
    { "粘液", "slime" },
    { "すらいむもーるど", "slime mold" },
    { "粘菌", "slime mold" },
    { "すりんぐ", "sling" },
    { "投石帯", "sling" },
    { "小さなみみっく", "small mimic" },
    { "すねーく", "snake" },
    { "はぶ", "snake" },
    { "へび", "snake" },
    { "蛇", "snake" },
    { "すにっかーすにー", "snickersnee" },
    { "刃渡り長刀", "snickersnee" },
    { "そこばん", "sokoban" },
    { "倉庫番", "sokoban" },
    { "そるじゃー", "soldier" },
    { "兵士", "soldier" },
    { "そるじゃーあんと", "soldier ant" },
    { "兵隊蟻", "soldier ant" },
    { "そーさらー", "sorcerer" },
    { "妖術師", "sorcerer" },
    { "そーされす", "sorceress" },
    { "妖術女", "sorceress" },
    { "すぱっと", "spat" },
    { "脚甲", "spat" },
    { "すぴあ", "spear" },
    { "槍", "spear" },
    { "すぺれおろじすと", "speleologist" },
    { "どうくつがくしゃ", "speleologist" },
    { "洞穴学者", "speleologist" },
    { "洞窟学者", "speleologist" },
    { "すぺるぶっく", "spellbook" },
    { "魔法書", "spellbook" },
    { "すぺらんかー", "spelunker" },
    { "たんけんしゃ", "spelunker" },
    { "探検者", "spelunker" },
    { "洞窟探検家", "spelunker" },
    { "すぺたむ", "spetum" },
    { "三叉槍", "spetum" },
    { "すふぃあ", "sphere" },
    { "氷の球体", "sphere" },
    { "炎の球体", "sphere" },
    { "球体", "sphere" },
    { "電撃の球体", "sphere" },
    { "すぱいだー", "spider" },
    { "巨大ぐも", "spider" },
    { "洞窟ぐも", "spider" },
    { "蜘蛛", "spider" },
    { "とげつきのおとしあな", "spiked pit" },
    { "棘付き落とし穴", "spiked pit" },
    { "すぽあ", "spore" },
    { "包子がす", "spore" },
    { "胞子", "spore" },
    { "まだらじぇりー", "spotted jelly" },
    { "まだらぜりー", "spotted jelly" },
    { "まだらのじぇりー", "spotted jelly" },
    { "まだらのぜりー", "spotted jelly" },
    { "斑じぇりー", "spotted jelly" },
    { "斑ぜりー", "spotted jelly" },
    { "すくわぶる", "squabble" },
    { "口論", "squabble" },
    { "きしむゆかいた", "squeaky board" },
    { "軋む床板", "squeaky board" },
    { "すたっふ", "staff" },
    { "杖", "staff" },
    { "あすくれぴおすのつえ", "staff of aesculapius" },
    { "あすくれぴおすの杖", "staff of aesculapius" },
    { "すたっふおぶあすくれぴおす", "staff of aesculapius" },
    { "かいだん", "stair" },
    { "かいだんくだり", "stair" },
    { "かいだんのぼり", "stair" },
    { "くだりかいだん", "stair" },
    { "くだりはしご", "stair" },
    { "すてあ", "stair" },
    { "のぼりかいだん", "stair" },
    { "のぼりはしご", "stair" },
    { "はしご", "stair" },
    { "上りはしご", "stair" },
    { "上り階段", "stair" },
    { "上階段", "stair" },
    { "下りはしご", "stair" },
    { "下り階段", "stair" },
    { "下階段", "stair" },
    { "梯子", "stair" },
    { "階段", "stair" },
    { "階段上り", "stair" },
    { "階段下り", "stair" },
    { "すとーかー", "stalker" },
    { "潜伏者", "stalker" },
    { "追跡者", "stalker" },
    { "すたちゅー", "statue" },
    { "石像", "statue" },
    { "蒸気の渦", "steam vortex" },
    { "すてそすこーぷ", "stethoscope" },
    { "聴診器", "stethoscope" },
    { "すてぃれっと", "stiletto" },
    { "刺突短剣", "stiletto" },
    { "すてぃんぐ", "sting" },
    { "岩石巨人", "stone giant" },
    { "すとーんごーれむ", "stone golem" },
    { "岩のごーれむ", "stone golem" },
    { "雷の巨人", "storm giant" },
    { "すとーむぶりんがー", "stormbringer" },
    { "すとれんじ", "strange" },
    { "奇妙", "strange" },
    { "きみょうなぶったい", "strange object" },
    { "奇妙な物体", "strange object" },
    { "すとろーごーれむ", "straw golem" },
    { "藁ごーれむ", "straw golem" },
    { "藁のごーれむ", "straw golem" },
    { "すとりっぷりんぐ", "stripling" },
    { "てじなし", "stripling" },
    { "わかきたておとめ", "stripling" },
    { "手品師", "stripling" },
    { "若き盾乙女", "stripling" },
    { "若輩", "stripling" },
    { "すちゅーでんと", "student" },
    { "学生", "student" },
    { "ひのたつじん", "student of fire" },
    { "ほのおのすちゅーでんと", "student of fire" },
    { "火の学生", "student of fire" },
    { "火の達人", "student of fire" },
    { "かねのつかいて", "student of metals" },
    { "きんぞくのすちゅーでんと", "student of metals" },
    { "金の使い手", "student of metals" },
    { "金属の学生", "student of metals" },
    { "いしのすちゅーでんと", "student of stones" },
    { "つちのつかいて", "student of stones" },
    { "土の使い手", "student of stones" },
    { "石の学生", "student of stones" },
    { "みずのすちゅーでんと", "student of waters" },
    { "みずのつかいて", "student of waters" },
    { "水の使い手", "student of waters" },
    { "水の学生", "student of waters" },
    { "かぜのすちゅーでんと", "student of winds" },
    { "きのたつじん", "student of winds" },
    { "木の達人", "student of winds" },
    { "風の学生", "student of winds" },
    { "さきゅばす", "succubus" },
    { "夢魔", "succubus" },
    { "よろいまたはぼうぐ", "suit or piece of armor" },
    { "鎧または防具", "suit or piece of armor" },
    { "さんそーど", "sunsword" },
    { "太陽剣", "sunsword" },
    { "すさのお", "susano*o" },
    { "けんかくおとめ", "swashbuckler" },
    { "すわっしゅばっくらー", "swashbuckler" },
    { "ようじゅつし", "swashbuckler" },
    { "伊達男剣士", "swashbuckler" },
    { "剣客乙女", "swashbuckler" },
    { "妖術師", "swashbuckler" },
    { "そーど", "sword" },
    { "剣", "sword" },
    { "たんこう", "tanko" },
    { "短甲", "tanko" },
    { "てれふぉん", "telephone" },
    { "電話", "telephone" },
    { "てれすこーぷ", "telescope" },
    { "望遠鏡", "telescope" },
    { "てれび", "television" },
    { "てれびじょん", "television" },
    { "しんまい", "tenderfoot" },
    { "てんだーふっと", "tenderfoot" },
    { "新米", "tenderfoot" },
    { "てんぐ", "tengu" },
    { "天狗", "tengu" },
    { "そーまたーじ", "thaumaturge" },
    { "奇術師範", "thaumaturge" },
    { "ざれでぃ", "the lady" },
    { "貴婦人", "the lady" },
    { "おおどろぼう", "thief" },
    { "しーふ", "thief" },
    { "大泥棒", "thief" },
    { "盗人", "thief" },
    { "とんぐどくらぶ", "thonged club" },
    { "革紐付き棍棒", "thonged club" },
    { "とーと", "thoth" },
    { "とーと・あもん", "thoth amon" },
    { "とーすあもん", "thoth*amon" },
    { "とーと・あもん", "thoth*amon" },
    { "ぎょくざ", "throne" },
    { "玉座", "throne" },
    { "すろーいんぐすたー", "throwing star" },
    { "投げ星", "throwing star" },
    { "さぐ", "thug" },
    { "ちんぴら", "thug" },
    { "暴漢", "thug" },
    { "てぃあまっと", "tiamat" },
    { "てぃふ", "tiff" },
    { "小競り合い", "tiff" },
    { "たいがー", "tiger" },
    { "虎", "tiger" },
    { "てぃん", "tin" },
    { "缶詰", "tin" },
    { "てぃんおーぷなー", "tin opener" },
    { "缶切り", "tin opener" },
    { "てぃにんぐきっと", "tinning kit" },
    { "缶詰道具", "tinning kit" },
    { "たいたん", "titan" },
    { "たいたのせあ", "titanothere" },
    { "たいたのてれ", "titanothere" },
    { "ちたのぜあ", "titanothere" },
    { "とぱーず", "topaz" },
    { "黄玉", "topaz" },
    { "とう", "tou" },
    { "塔", "tou" },
    { "たっちすとーん", "touch*stone" },
    { "触石", "touch*stone" },
    { "つーりすと", "tourist" },
    { "旅行者", "tourist" },
    { "観光客", "tourist" },
    { "たおる", "towel" },
    { "たわー", "tower" },
    { "塔", "tower" },
    { "やみのとう", "tower of darkness" },
    { "闇の塔", "tower of darkness" },
    { "せんどう", "trailblazer" },
    { "とれいるぶれいざー", "trailblazer" },
    { "先導", "trailblazer" },
    { "先導者", "trailblazer" },
    { "とらっぷどあ", "trap*door" },
    { "落とし戸", "trap*door" },
    { "とらっぱー", "trapper" },
    { "罠師", "trapper" },
    { "とらっぱーまたはるーかーあばゔ", "trapper or lurker above" },
    { "罠師または天井潜み", "trapper or lurker above" },
    { "とらべらー", "traveler" },
    { "りょこうしゃ", "traveler" },
    { "旅行者", "traveler" },
    { "道行き人", "traveler" },
    { "き", "tree" },
    { "木", "tree" },
    { "とらいでんと", "trident" },
    { "三叉戟", "trident" },
    { "とらいぷ", "tripe" },
    { "胃袋", "tripe" },
    { "とらいぷれーしょん", "tripe ration" },
    { "胃袋の配給", "tripe ration" },
    { "けっきょじん", "troglodyte" },
    { "とろぐろだいと", "troglodyte" },
    { "穴居人", "troglodyte" },
    { "とろる", "troll" },
    { "妖鬼", "troll" },
    { "つるぎ", "tsurugi" },
    { "大太刀", "tsurugi" },
    { "むらまさのけん", "tsurugi of muramasa" },
    { "村正の剣", "tsurugi of muramasa" },
    { "たーこいず", "turquoise" },
    { "青緑石", "turquoise" },
    { "青緑石", "turquoise*" },
    { "つーふらわー", "twoflower" },
    { "とぅーふらわー", "twoflower" },
    { "てゅーる", "tyr" },
    { "あんばーはるく", "umber hulk" },
    { "あんあーむどこんばっと", "unarmed combat" },
    { "素手戦闘", "unarmed combat" },
    { "ゆにこーん", "unicorn" },
    { "一角獣", "unicorn" },
    { "ゆにこーんほーん", "unicorn horn" },
    { "一角獣の角", "unicorn horn" },
    { "あんりこんのいたーど", "unreconnoitered" },
    { "未踏査", "unreconnoitered" },
    { "うるく=はい", "uruk*hai" },
    { "うるくはい", "uruk*hai" },
    { "うるく・はい", "uruk*hai" },
    { "うるくはい", "uruk-hai" },
    { "うるく・はい", "uruk-hai" },
    { "ゆーざー", "user" },
    { "利用者", "user" },
    { "ふろうしゃ", "vagrant" },
    { "ゔぇいぐらんと", "vagrant" },
    { "浮浪者", "vagrant" },
    { "ゔぁる", "val*" },
    { "わるきゅーれ", "valkyrie" },
    { "ゔぁる", "valkyrie" },
    { "ゔぁるきりー", "valkyrie" },
    { "戦乙女", "valkyrie" },
    { "ゔぁんぱいあ", "vampire" },
    { "ゔぁんぱいあの長", "vampire" },
    { "吸血鬼", "vampire" },
    { "吸血こうもり", "vampire bat" },
    { "べのむ", "venom" },
    { "毒液", "venom" },
    { "ゔぃーなす", "venus" },
    { "金星", "venus" },
    { "紫きのこ", "violet fungus" },
    { "ゔらど", "vlad" },
    { "伯爵", "vlad" },
    { "吸血鬼ゔらど", "vlad the impaler" },
    { "ゔぉーぱる", "vorpal" },
    { "斬首", "vorpal" },
    { "えねるぎーの渦", "vortex" },
    { "ぼるてっくす", "vortex" },
    { "渦", "vortex" },
    { "ぼるてぃしーず", "vortices" },
    { "渦群", "vortices" },
    { "ゔぉうるじゅ", "voulge" },
    { "長柄鉈", "voulge" },
    { "こうかいしゃ", "voyager" },
    { "ゔぉいえじゃー", "voyager" },
    { "航海者", "voyager" },
    { "ゔぁろっく", "vrock" },
    { "ゔろっく", "vrock" },
    { "わきざし", "wakizashi" },
    { "脇差", "wakizashi" },
    { "わんど", "wand" },
    { "魔法の杖", "wand" },
    { "ほうろうしゃ", "wanderer" },
    { "わんだらー", "wanderer" },
    { "放浪者", "wanderer" },
    { "旅の者", "wanderer" },
    { "うぉー", "war" },
    { "戦争", "war" },
    { "うぉーはんまー", "war*hammer" },
    { "戦槌", "war*hammer" },
    { "うぉーぐ", "warg" },
    { "わーぐ", "warg" },
    { "怪狼", "warg" },
    { "戦闘用の馬", "warhorse" },
    { "いくさおとめ", "warrior" },
    { "うぉりあー", "warrior" },
    { "しょうかんし", "warrior" },
    { "召喚師", "warrior" },
    { "戦乙女", "warrior" },
    { "戦士", "warrior" },
    { "武人", "warrior" },
    { "うぉっち", "watch" },
    { "番兵", "watch" },
    { "見張りの隊長", "watch captain" },
    { "見張り", "watchman" },
    { "うぉーたー", "water" },
    { "みず", "water" },
    { "水", "water" },
    { "うぉーたーでーもん", "water demon" },
    { "水の悪魔", "water demon" },
    { "水の魔神", "water demon" },
    { "水の精", "water elemental" },
    { "うぉーたーもかしん", "water moccasin" },
    { "水へび", "water moccasin" },
    { "水もかしん", "water moccasin" },
    { "みずのにんふ", "water nymph" },
    { "水のにんふ", "water nymph" },
    { "うぉーたーとろる", "water troll" },
    { "水のとろる", "water troll" },
    { "水棲妖鬼", "water troll" },
    { "うぇいふぇあらー", "wayfarer" },
    { "りょこうしゃ", "wayfarer" },
    { "旅行者", "wayfarer" },
    { "道中人", "wayfarer" },
    { "うぇぽん", "weapon" },
    { "武器", "weapon" },
    { "うぇぶ", "web" },
    { "蜘蛛の巣", "web" },
    { "うぇあ", "were" },
    { "ねずみ人間", "were" },
    { "狼男種", "were" },
    { "獣人", "were" },
    { "うぇあ", "were*" },
    { "じゃっかる人間", "werejackal" },
    { "ねずみ人間", "wererat" },
    { "狼人間", "werewolf" },
    { "うぇっとたおる", "wet towel" },
    { "ぬれたたおる", "wet towel" },
    { "ほいっする", "whistle" },
    { "笛", "whistle" },
    { "わいとどらごん", "white dragon" },
    { "白どらごん", "white dragon" },
    { "白ゆにこーん", "white unicorn" },
    { "ほわいとはんでっどしーるど", "white-handed shield" },
    { "白手の盾", "white-handed shield" },
    { "ばろう・わいと", "wight" },
    { "わいと", "wight" },
    { "わいと種", "wight" },
    { "うぃん", "win" },
    { "勝利", "win" },
    { "羽のあるがーごいる", "winged gargoyle" },
    { "うぃなー", "winner" },
    { "勝者", "winner" },
    { "うぃにんぐ", "winning" },
    { "勝ち越し", "winning" },
    { "うぃんたーうるふ", "winter wolf" },
    { "冬狼", "winter wolf" },
    { "冬狼の子", "winter wolf cub" },
    { "うぃず", "wiz*" },
    { "いぇんだーの魔法使い", "wizard" },
    { "うぃざーど", "wizard" },
    { "魔法使い", "wizard" },
    { "魔術", "wizard" },
    { "いぇんだーの魔法使い", "wizard of yendor" },
    { "いぇんだーの魔術師", "wizard of yendor" },
    { "うぃざーどおぶいぇんだー", "wizard of yendor" },
    { "うるふ", "wolf" },
    { "おおかみ", "wolf" },
    { "冬狼", "wolf" },
    { "冬狼の子", "wolf" },
    { "狼", "wolf" },
    { "うるふきゅぶ", "wolf cub" },
    { "おおかみのこ", "wolf cub" },
    { "狼の子", "wolf cub" },
    { "うるふずべいん", "wolfsbane" },
    { "とりかぶと", "wolfsbane" },
    { "うっどごーれむ", "wood golem" },
    { "木のごーれむ", "wood golem" },
    { "きのにんふ", "wood nymph" },
    { "木のにんふ", "wood nymph" },
    { "うっどちゃっく", "woodchuck" },
    { "りす", "woodchuck" },
    { "森のえるふ", "woodland-elf" },
    { "みみず", "worm" },
    { "ろんぐわーむの子供", "worm" },
    { "わーむ", "worm" },
    { "わーむとぅーす", "worm tooth" },
    { "虫歯牙", "worm tooth" },
    { "れいす", "wraith" },
    { "わんぱす", "wumpus" },
    { "わんぷすの洞窟", "wumpus" },
    { "怪獣わんぱす", "wumpus" },
    { "ざん", "xan" },
    { "ぞーん", "xorn" },
    { "いくそす", "xoth" },
    { "ざす", "xoth" },
    { "ぞす", "xoth" },
    { "や", "ya" },
    { "和矢", "ya" },
    { "いぇーのーぐ", "yeenoghu" },
    { "いーのぐ", "yeenoghu" },
    { "いーのーぐ", "yeenoghu" },
    { "いえろーどらごん", "yellow dragon" },
    { "黄色どらごん", "yellow dragon" },
    { "黄色い光", "yellow light" },
    { "黄色もーるど", "yellow mold" },
    { "いぇてぃ", "yeti" },
    { "雪男", "yeti" },
    { "ゆがけ", "yugake" },
    { "ゆみ", "yumi" },
    { "和弓", "yumi" },
    { "ぞんび", "zombi" },
    { "ぞーくみっど", "zorkmid" },
    { "通貨", "zorkmid" },
    { "ぞーくみっど", "zorkmid*" },
    { "ずるてぃ", "zruty" },
    { "ずるーてぃ", "zruty" },
    /* アーティファクト */
    { "えくすかりばー", "excalibur" },
    { "すとーむぶりんがー", "stormbringer" },
    { "みょるにる", "mjollnir" },
    { "みゅるにーる", "mjollnir" },
    { "くりーばー", "cleaver" },
    { "ぐりむとぅーす", "grimtooth" },
    { "おーくりすと", "orcrist" },
    { "すてぃんぐ", "sting" },
    { "まじっくべいん", "magicbane" },
    { "ふろすとぶらんど", "frost brand" },
    { "ふぁいあぶらんど", "fire brand" },
    { "どらごんべいん", "dragonbane" },
    { "デーモンベイン", "demonbane" },
    { "でーもんべいん", "demonbane" },
    { "うぇあべいん", "werebane" },
    { "ぐれいずわんでぃる", "grayswandir" },
    { "ぐれいすわんだー", "grayswandir" },
    { "じゃいあんとすれいやー", "giantslayer" },
    { "おうがすまっしゃー", "ogresmasher" },
    { "おーがすまっしゃー", "ogresmasher" },
    { "とろるずべいん", "trollsbane" },
    { "とろるすべーん", "trollsbane" },
    { "ゔぉーぱるぶれーど", "vorpal blade" },
    { "ぼーぱるぶれーど", "vorpal blade" },
    { "すにっかーずにー", "snickersnee" },
    { "さんそーど", "sunsword" },
    /* クエストアーティファクト */
    { "たんちのおーぶ", "orb of detection" },
    { "たんちのオーブ", "orb of detection" },
    { "たんさくのおーぶ", "orb of detection" },
    { "たんさくのオーブ", "orb of detection" },
    { "あーりまんのしんぞう", "heart of ahriman" },
    { "あーりまんの心臓", "heart of ahriman" },
    { "ちからのおうしゃく", "sceptre of might" },
    { "ちからの王笏", "sceptre of might" },
    { "けんりょくのしゃく", "sceptre of might" },
    { "けんりょくの笏", "sceptre of might" },
    { "あすくれぴおすのつえ", "staff of aesculapius" },
    { "あすくれぴおすの杖", "staff of aesculapius" },
    { "まーりんのまほうのかがみ", "magic mirror of merlin" },
    { "まーりんの魔法 of 鏡", "magic mirror of merlin" },
    { "まーりんの魔法の鏡", "magic mirror of merlin" },
    { "おーばーわーるどのめ", "eyes of the overworld" },
    { "おーばーわーるどの目", "eyes of the overworld" },
    { "ちょうせかいのめ", "eyes of the overworld" },
    { "ちょうせかいの目", "eyes of the overworld" },
    { "しんせいのそうぼう", "mitre of holiness" },
    { "しんせいの僧帽", "mitre of holiness" },
    { "せいなるかんむり", "mitre of holiness" },
    { "せいなる冠", "mitre of holiness" },
    { "でぃあなのちょうきゅう", "longbow of diana" },
    { "でぃあなの長弓", "longbow of diana" },
    { "とうぞくじゅつのますたーきー", "master key of thievery" },
    { "とうぞくじゅつのマスターキー", "master key of thievery" },
    { "とうぞくのますたーきー", "master key of thievery" },
    { "とうぞくのマスターキー", "master key of thievery" },
    { "むらまさのけん", "tsurugi of muramasa" },
    { "むらまさの剣", "tsurugi of muramasa" },
    { "むらまさのかたな", "tsurugi of muramasa" },
    { "むらまさの刀", "tsurugi of muramasa" },
    { "ぷらちないぇんだーじるしえくすぷれすかーど", "platinum yendorian express card" },
    { "ぷらちないぇんだー印えくすぷれすかーど", "platinum yendorian express card" },
    { "うんめいのおーぶ", "orb of fate" },
    { "うんめいのオーブ", "orb of fate" },
    { "えちおぴかのめ", "eye of the aethiopica" },
    { "えちおぴかの目", "eye of the aethiopica" },
    { "えちおぴあのめ", "eye of the aethiopica" },
    { "えちおぴあの目", "eye of the aethiopica" },
};

staticfn boolean
jp_data_lookup_has_nonascii(const char *s)
{
    while (*s) {
        if (((uchar) *s) & 0x80U)
            return TRUE;
        ++s;
    }
    return FALSE;
}

staticfn void
jp_data_lookup_normalize(char *s)
{
    utf8_katakana_to_hiragana(s);
    /* 中黒（U+30FB、UTF-8バイト列: \xe3\x83\xbb）を除去する */
    {
        char *p = s, *q = s;
        while (*p != '\0') {
            /*
             * 境界外アクセスとナル文字飛び越しを防ぐため、
             * p[1] や p[2] が \0 でないことを必ず確認してからマルチバイト比較を行う
             */
            if ((uchar)p[0] == 0xe3U && p[1] != '\0' && (uchar)p[1] == 0x83U 
                                     && p[2] != '\0' && (uchar)p[2] == 0xbbU) {
                p += 3;
                continue;
            }
            *q++ = *p++;
        }
        *q = '\0';
    }
    (void) mungspaces(s);
}

boolean
jp_data_lookup_key_from_japanese(const char *input, char *out, size_t outsz)
{
    char normalized[BUFSZ];
    const char *key;
    int i;

    if (!input || !*input || !out || outsz == 0)
        return FALSE;
    if (!jp_data_lookup_has_nonascii(input))
        return FALSE;

    strncpy(normalized, input, sizeof normalized - 1);
    normalized[sizeof normalized - 1] = '\0';
    jp_data_lookup_normalize(normalized);
    key = trimspaces(normalized);
    if (!*key)
        return FALSE;

    for (i = 0; i < SIZE(jp_data_lookup_aliases); ++i) {
        if (!strcmp(key, jp_data_lookup_aliases[i].jp_key)) {
            strncpy(out, jp_data_lookup_aliases[i].en_key, outsz - 1);
            out[outsz - 1] = '\0';
            return TRUE;
        }
    }
    return FALSE;
}

