/* Modified by NetHackJP contributor @satokiyon; latest change date: 2026-06-13. */
#include "config.h"
#include "permonst.h"

/*
 * モンスター表示名の日本語テーブル。
 * 内部ID解決は英語 pmnames[] を使い続けるため、表示専用で参照する。
 */
static const char *const mon_jp_names[NUMMONS][NUM_MGENDERS] = {
    [PM_GIANT_ANT] = { 0, 0, "巨大蟻" },
    [PM_KILLER_BEE] = { 0, 0, "殺人蜂" },
    [PM_SOLDIER_ANT] = { 0, 0, "兵隊蟻" },
    [PM_FIRE_ANT] = { 0, 0, "火蟻" },
    [PM_GIANT_BEETLE] = { 0, 0, "巨大カブト虫" },
    [PM_QUEEN_BEE] = { 0, 0, "女王蜂" },
    [PM_ACID_BLOB] = { 0, 0, "酸のブロッブ" },
    [PM_QUIVERING_BLOB] = { 0, 0, "震えるブロッブ" },
    [PM_GELATINOUS_CUBE] = { 0, 0, "ゼラチンキューブ" },
    [PM_CHICKATRICE] = { 0, 0, "チカトリス" },
    [PM_COCKATRICE] = { 0, 0, "コカトリス" },
    [PM_PYROLISK] = { 0, 0, "ピロリスク" },
    [PM_JACKAL] = { 0, 0, "ジャッカル" },
    [PM_FOX] = { 0, 0, "狐" },
    [PM_COYOTE] = { 0, 0, "コヨーテ" },
    [PM_LITTLE_DOG] = { 0, 0, "仔犬" },
    [PM_DOG] = { 0, 0, "犬" },
    [PM_LARGE_DOG] = { 0, 0, "大きな犬" },
    [PM_WOLF] = { 0, 0, "狼" },
    [PM_WINTER_WOLF] = { 0, 0, "冬狼" },
    [PM_DINGO] = { 0, 0, "野犬" },
    [PM_WEREJACKAL] = { 0, 0, "ジャッカル人間" },
    [PM_WERERAT] = { 0, 0, "ねずみ人間" },
    [PM_WEREWOLF] = { 0, 0, "狼人間" },
    [PM_WINTER_WOLF_CUB] = { 0, 0, "冬狼の子" },
    [PM_WARG] = { 0, 0, "ワーグ" },
    [PM_HELL_HOUND_PUP] = { 0, 0, "ヘルハウンドの仔" },
    [PM_HELL_HOUND] = { 0, 0, "ヘルハウンド" },
    [PM_BAT] = { 0, 0, "こうもり" },
    [PM_GIANT_BAT] = { 0, 0, "巨大こうもり" },
    [PM_RAVEN] = { 0, 0, "オオガラス" },
    [PM_VAMPIRE_BAT] = { 0, 0, "吸血こうもり" },
    [PM_SEWER_RAT] = { 0, 0, "ドブネズミ" },
    [PM_GIANT_RAT] = { 0, 0, "巨大ネズミ" },
    [PM_RABID_RAT] = { 0, 0, "兇暴ネズミ" },
    [PM_CAVE_SPIDER] = { 0, 0, "洞窟グモ" },
    [PM_GIANT_SPIDER] = { 0, 0, "巨大グモ" },
    [PM_GAS_SPORE] = { 0, 0, "包子ガス" },
    [PM_FLOATING_EYE] = { 0, 0, "さまよう目" },
    [PM_FREEZING_SPHERE] = { 0, 0, "氷の球体" },
    [PM_FLAMING_SPHERE] = { 0, 0, "炎の球体" },
    [PM_SHOCKING_SPHERE] = { 0, 0, "電撃の球体" },
    [PM_STALKER] = { 0, 0, "ストーカー" },
    [PM_AIR_ELEMENTAL] = { 0, 0, "風の精" },
    [PM_FIRE_ELEMENTAL] = { 0, 0, "火の精" },
    [PM_EARTH_ELEMENTAL] = { 0, 0, "土の精" },
    [PM_WATER_ELEMENTAL] = { 0, 0, "水の精" },
    [PM_LICHEN] = { 0, 0, "苔の怪物" },
    [PM_BROWN_MOLD] = { 0, 0, "茶色モールド" },
    [PM_YELLOW_MOLD] = { 0, 0, "黄色モールド" },
    [PM_GREEN_MOLD] = { 0, 0, "緑モールド" },
    [PM_RED_MOLD] = { 0, 0, "赤色モールド" },
    [PM_SHRIEKER] = { 0, 0, "シュリーカー" },
    [PM_VIOLET_FUNGUS] = { 0, 0, "紫キノコ" },
    [PM_KITTEN] = { 0, 0, "小猫" },
    [PM_HOUSECAT] = { 0, 0, "家猫" },
    [PM_JAGUAR] = { 0, 0, "ジャガー" },
    [PM_LYNX] = { 0, 0, "山猫" },
    [PM_PANTHER] = { 0, 0, "パンサー" },
    [PM_LARGE_CAT] = { 0, 0, "大きな猫" },
    [PM_TIGER] = { 0, 0, "虎" },
    [PM_PLAINS_CENTAUR] = { 0, 0, "草原のケンタウロス" },
    [PM_FOREST_CENTAUR] = { 0, 0, "森のケンタウロス" },
    [PM_MOUNTAIN_CENTAUR] = { 0, 0, "山のケンタウロス" },
    [PM_ROCK_MOLE] = { 0, 0, "岩もぐら" },
    [PM_WOODCHUCK] = { 0, 0, "リス" },
    [PM_CENTIPEDE] = { 0, 0, "ムカデ" },
    [PM_SCORPION] = { 0, 0, "サソリ" },
    [PM_LURKER_ABOVE] = { 0, 0, "ラーカー" },
    [PM_TRAPPER] = { 0, 0, "トラッパー" },
    [PM_PONY] = { 0, 0, "仔馬" },
    [PM_HORSE] = { 0, 0, "馬" },
    [PM_WARHORSE] = { 0, 0, "戦闘用の馬" },
    [PM_FOG_CLOUD] = { 0, 0, "霧の雲" },
    [PM_DUST_VORTEX] = { 0, 0, "ほこりの渦" },
    [PM_ICE_VORTEX] = { 0, 0, "氷の渦" },
    [PM_ENERGY_VORTEX] = { 0, 0, "エネルギーの渦" },
    [PM_STEAM_VORTEX] = { 0, 0, "蒸気の渦" },
    [PM_FIRE_VORTEX] = { 0, 0, "炎の渦" },
    [PM_BABY_LONG_WORM] = { 0, 0, "ロングワームの子供" },
    [PM_BABY_PURPLE_WORM] = { 0, 0, "紫ワームの子供" },
    [PM_PURPLE_WORM] = { 0, 0, "紫ワーム" },
    [PM_GRID_BUG] = { 0, 0, "グリッドバグ" },
    [PM_XAN] = { 0, 0, "ザン" },
    [PM_YELLOW_LIGHT] = { 0, 0, "黄色い光" },
    [PM_BLACK_LIGHT] = { 0, 0, "黒い光" },
    [PM_ZRUTY] = { 0, 0, "ズルティ" },
    [PM_COUATL] = { 0, 0, "コウアトル" },
    [PM_ALEAX] = { 0, 0, "アレアックス" },
    [PM_ANGEL] = { 0, 0, "天使" },
    [PM_KI_RIN] = { 0, 0, "麒麟" },
    [PM_ARCHON] = { 0, 0, "アルコン" },
    [PM_GOBLIN] = { 0, 0, "ゴブリン" },
    [PM_HOBGOBLIN] = { 0, 0, "ホブゴブリン" },
    [PM_KOBOLD] = { 0, 0, "コボルド" },
    [PM_LARGE_KOBOLD] = { 0, 0, "大きなコボルド" },
    [PM_KOBOLD_LEADER] = { 0, 0, "コボルドの首領" },
    [PM_KOBOLD_SHAMAN] = { 0, 0, "コボルドの呪術師" },
    [PM_DWARF] = { 0, 0, "ドワーフ" },
    [PM_GNOME_LEADER] = { 0, 0, "ノームの首領" },
    [PM_GNOMISH_WIZARD] = { 0, 0, "ノームの魔法使い" },
    [PM_GNOME_RULER] = { 0, 0, "ノームの支配者" },
    [PM_DWARF_LEADER] = { 0, 0, "ドワーフの首領" },
    [PM_DWARF_RULER] = { 0, 0, "ドワーフの支配者" },
    [PM_DWARF_MUMMY] = { 0, 0, "ドワーフのミイラ" },
    [PM_DWARF_ZOMBIE] = { 0, 0, "ドワーフのゾンビ" },
    [PM_GNOME] = { 0, 0, "ノーム" },
    [PM_GNOME_MUMMY] = { 0, 0, "ノームのミイラ" },
    [PM_GNOME_ZOMBIE] = { 0, 0, "ノームのゾンビ" },
    [PM_ORC] = { 0, 0, "オーク" },
    [PM_HILL_ORC] = { 0, 0, "丘のオーク" },
    [PM_MORDOR_ORC] = { 0, 0, "モルドールのオーク" },
    [PM_URUK_HAI] = { 0, 0, "ウルク・ハイ" },
    [PM_ORC_CAPTAIN] = { 0, 0, "オークの隊長" },
    [PM_ORC_SHAMAN] = { 0, 0, "オークの呪術師" },
    [PM_ORC_ZOMBIE] = { 0, 0, "オークのゾンビ" },
    [PM_ORC_MUMMY] = { 0, 0, "オークのミイラ" },
    [PM_ELF] = { 0, 0, "エルフ" },
    [PM_WOODLAND_ELF] = { 0, 0, "森のエルフ" },
    [PM_GREEN_ELF] = { 0, 0, "緑エルフ" },
    [PM_GREY_ELF] = { 0, 0, "灰色エルフ" },
    [PM_ELF_NOBLE] = { 0, 0, "エルフの貴族" },
    [PM_ELVEN_MONARCH] = { 0, 0, "エルフの君主" },
    [PM_ELF_MUMMY] = { 0, 0, "エルフのミイラ" },
    [PM_ELF_ZOMBIE] = { 0, 0, "エルフのゾンビ" },
    [PM_HUMAN] = { 0, 0, "人間" },
    [PM_HUMAN_WERERAT] = { 0, 0, "ねずみ人間" },
    [PM_HUMAN_WEREJACKAL] = { 0, 0, "ジャッカル人間" },
    [PM_HUMAN_WEREWOLF] = { 0, 0, "狼人間" },
    [PM_ARCHEOLOGIST] = { 0, 0, "考古学者" },
    [PM_BARBARIAN] = { 0, 0, "野蛮人" },
    [PM_CAVE_DWELLER] = { 0, 0, "洞窟人" },
    [PM_HEALER] = { 0, 0, "治療師" },
    [PM_KNIGHT] = { 0, 0, "騎士" },
    [PM_MONK] = { 0, 0, "武闘家" },
    [PM_CLERIC] = { 0, 0, "司祭" },
    [PM_RANGER] = { 0, 0, "レンジャー" },
    [PM_ROGUE] = { 0, 0, "盗賊" },
    [PM_SAMURAI] = { 0, 0, "侍" },
    [PM_TOURIST] = { 0, 0, "観光客" },
    [PM_VALKYRIE] = { 0, 0, "ワルキューレ" },
    [PM_WIZARD] = { 0, 0, "魔法使い" },
    [PM_STUDENT] = { 0, 0, "学生" },
    [PM_CHIEFTAIN] = { 0, 0, "首領" },
    [PM_NEANDERTHAL] = { 0, 0, "ネアンデルタール人" },
    [PM_ATTENDANT] = { 0, 0, "随行員" },
    [PM_PAGE] = { 0, 0, "小姓" },
    [PM_ABBOT] = { 0, 0, "師範" },
    [PM_ACOLYTE] = { 0, 0, "侍者" },
    [PM_HUNTER] = { 0, 0, "ハンター" },
    [PM_THUG] = { 0, 0, "ちんぴら" },
    [PM_NINJA] = { 0, 0, "忍者" },
    [PM_ROSHI] = { 0, 0, "浪士" },
    [PM_GUIDE] = { 0, 0, "ガイド" },
    [PM_WARRIOR] = { 0, 0, "戦士" },
    [PM_APPRENTICE] = { 0, 0, "実習生" },
    [PM_HUMAN_MUMMY] = { 0, 0, "人間のミイラ" },
    [PM_HUMAN_ZOMBIE] = { 0, 0, "人間のゾンビ" },
    [PM_GIANT] = { 0, 0, "巨人" },
    [PM_STONE_GIANT] = { 0, 0, "岩石巨人" },
    [PM_HILL_GIANT] = { 0, 0, "丘の巨人" },
    [PM_FIRE_GIANT] = { 0, 0, "炎の巨人" },
    [PM_FROST_GIANT] = { 0, 0, "吹雪の巨人" },
    [PM_STORM_GIANT] = { 0, 0, "雷の巨人" },
    [PM_TITAN] = { 0, 0, "タイタン" },
    [PM_MINOTAUR] = { 0, 0, "ミノタウロス" },
    [PM_JABBERWOCK] = { 0, 0, "ジャバウォック" },
    [PM_GIANT_MUMMY] = { 0, 0, "巨人のミイラ" },
    [PM_GIANT_ZOMBIE] = { 0, 0, "巨人のゾンビ" },
    [PM_ETTIN] = { 0, 0, "エティン" },
    [PM_ETTIN_MUMMY] = { 0, 0, "エティンのミイラ" },
    [PM_ETTIN_ZOMBIE] = { 0, 0, "エティンのゾンビ" },
    [PM_TROLL] = { 0, 0, "トロル" },
    [PM_ICE_TROLL] = { 0, 0, "氷のトロル" },
    [PM_ROCK_TROLL] = { 0, 0, "岩のトロル" },
    [PM_WATER_TROLL] = { 0, 0, "水のトロル" },
    [PM_OLOG_HAI] = { 0, 0, "オログハイ" },
    [PM_UMBER_HULK] = { 0, 0, "アンバーハルク" },
    [PM_OGRE] = { 0, 0, "オーガ" },
    [PM_OGRE_LEADER] = { 0, 0, "オーガの首領" },
    [PM_OGRE_TYRANT] = { 0, 0, "オーガの暴君" },
    [PM_DISPLACER_BEAST] = { 0, 0, "ディスプレイサービースト" },
    [PM_GHOST] = { 0, 0, "幽霊" },
    [PM_MEDUSA] = { 0, 0, "メデューサ" },
    [PM_WIZARD_OF_YENDOR] = { 0, 0, "イェンダーの魔法使い" },
    [PM_CROESUS] = { 0, 0, "クロイソス" },
    [PM_DOPPELGANGER] = { 0, 0, "ドッペルゲンガー" },
    [PM_SHOPKEEPER] = { 0, 0, "店主" },
    [PM_GUARD] = { 0, 0, "番兵" },
    [PM_PRISONER] = { 0, 0, "囚人" },
    [PM_ORACLE] = { 0, 0, "賢者" },
    [PM_ALIGNED_CLERIC] = { 0, 0, "神官" },
    [PM_HIGH_CLERIC] = { 0, 0, "高位神官" },
    [PM_SOLDIER] = { 0, 0, "兵士" },
    [PM_SERGEANT] = { 0, 0, "下士官" },
    [PM_NURSE] = { 0, 0, "看護婦" },
    [PM_LIEUTENANT] = { 0, 0, "副官" },
    [PM_CAPTAIN] = { 0, 0, "指揮官" },
    [PM_WATCHMAN] = { 0, 0, "見張り" },
    [PM_WATCH_CAPTAIN] = { 0, 0, "見張りの隊長" },
    [PM_SHADE] = { 0, 0, "影" },
    [PM_WATER_DEMON] = { 0, 0, "水の魔神" },
    [PM_AMOROUS_DEMON] = { 0, 0, "愛の悪魔" },
    [PM_HORNED_DEVIL] = { 0, 0, "角のある悪魔" },
    [PM_ERINYS] = { 0, 0, "イリニス" },
    [PM_BARBED_DEVIL] = { 0, 0, "棘の悪魔" },
    [PM_MARILITH] = { 0, 0, "マリリス" },
    [PM_VROCK] = { 0, 0, "ヴァロック" },
    [PM_HEZROU] = { 0, 0, "ヘズロウ" },
    [PM_BONE_DEVIL] = { 0, 0, "骨の悪魔" },
    [PM_ICE_DEVIL] = { 0, 0, "氷の悪魔" },
    [PM_NALFESHNEE] = { 0, 0, "ナルフェシニ" },
    [PM_PIT_FIEND] = { 0, 0, "穴の悪霊" },
    [PM_SANDESTIN] = { 0, 0, "サンデスティン" },
    [PM_BALROG] = { 0, 0, "バルログ" },
    [PM_JUIBLEX] = { 0, 0, "ジョウビレックス" },
    [PM_YEENOGHU] = { 0, 0, "イーノグ" },
    [PM_ORCUS] = { 0, 0, "オーケス" },
    [PM_GERYON] = { 0, 0, "ゲーリュオーン" },
    [PM_DISPATER] = { 0, 0, "ディスペータ" },
    [PM_BAALZEBUB] = { 0, 0, "ベルゼブブ" },
    [PM_ASMODEUS] = { 0, 0, "アスモデウス" },
    [PM_DEMOGORGON] = { 0, 0, "デモゴルゴン" },
    [PM_DEATH] = { 0, 0, "デス" },
    [PM_PESTILENCE] = { 0, 0, "ペスティレンス" },
    [PM_FAMINE] = { 0, 0, "フェミン" },
    [PM_MAIL_DAEMON] = { 0, 0, "メイルデーモン" },
    [PM_DJINNI] = { 0, 0, "風のジン" },
    [PM_VLAD_THE_IMPALER] = { 0, 0, "吸血鬼ヴラド" },
    [PM_GARGOYLE] = { 0, 0, "ガーゴイル" },
    [PM_WINGED_GARGOYLE] = { 0, 0, "羽のあるガーゴイル" },
    [PM_KEYSTONE_KOP] = { 0, 0, "警備員" },
    [PM_KOP_SERGEANT] = { 0, 0, "巡査" },
    [PM_KOP_LIEUTENANT] = { 0, 0, "巡査部長" },
    [PM_KOP_KAPTAIN] = { 0, 0, "警部補" },
    [PM_LICH] = { 0, 0, "リッチ" },
    [PM_DEMILICH] = { 0, 0, "デミリッチ" },
    [PM_MASTER_LICH] = { 0, 0, "マスターリッチ" },
    [PM_ARCH_LICH] = { 0, 0, "アーチリッチ" },
    [PM_HOBBIT] = { 0, 0, "ホビット" },
    [PM_BUGBEAR] = { 0, 0, "バグベアー" },
    [PM_GHOUL] = { 0, 0, "グール" },
    [PM_GREMLIN] = { 0, 0, "グレムリン" },
    [PM_LEPRECHAUN] = { 0, 0, "レプラコーン" },
    [PM_SMALL_MIMIC] = { 0, 0, "小さなミミック" },
    [PM_LARGE_MIMIC] = { 0, 0, "大きなミミック" },
    [PM_GIANT_MIMIC] = { 0, 0, "巨大なミミック" },
    [PM_WOOD_NYMPH] = { 0, 0, "木のニンフ" },
    [PM_WATER_NYMPH] = { 0, 0, "水のニンフ" },
    [PM_MOUNTAIN_NYMPH] = { 0, 0, "山のニンフ" },
    [PM_GARTER_SNAKE] = { 0, 0, "小さなヘビ" },
    [PM_SNAKE] = { 0, 0, "ヘビ" },
    [PM_WATER_MOCCASIN] = { 0, 0, "水ヘビ" },
    [PM_PYTHON] = { 0, 0, "ニシキヘビ" },
    [PM_PIT_VIPER] = { 0, 0, "ハブ" },
    [PM_COBRA] = { 0, 0, "コブラ" },
    [PM_RED_NAGA_HATCHLING] = { 0, 0, "赤色ナーガの雛" },
    [PM_BLACK_NAGA_HATCHLING] = { 0, 0, "黒ナーガの雛" },
    [PM_GOLDEN_NAGA_HATCHLING] = { 0, 0, "金色ナーガの雛" },
    [PM_GUARDIAN_NAGA_HATCHLING] = { 0, 0, "番兵ナーガの雛" },
    [PM_RED_NAGA] = { 0, 0, "赤色ナーガ" },
    [PM_BLACK_NAGA] = { 0, 0, "黒ナーガ" },
    [PM_GOLDEN_NAGA] = { 0, 0, "金色ナーガ" },
    [PM_GUARDIAN_NAGA] = { 0, 0, "番兵ナーガ" },
    [PM_QUANTUM_MECHANIC] = { 0, 0, "量子物理学者" },
    [PM_GENETIC_ENGINEER] = { 0, 0, "遺伝子工学者" },
    [PM_RUST_MONSTER] = { 0, 0, "錆の怪物" },
    [PM_DISENCHANTER] = { 0, 0, "吸魔の怪物" },
    [PM_MIND_FLAYER] = { 0, 0, "マインドフレア" },
    [PM_MASTER_MIND_FLAYER] = { 0, 0, "マスターマインドフレア" },
    [PM_MANES] = { 0, 0, "亡霊" },
    [PM_HOMUNCULUS] = { 0, 0, "ホムンクルス" },
    [PM_IMP] = { 0, 0, "インプ" },
    [PM_LEMURE] = { 0, 0, "レムレース" },
    [PM_QUASIT] = { 0, 0, "クアシト" },
    [PM_TENGU] = { 0, 0, "天狗" },
    [PM_BLUE_JELLY] = { 0, 0, "青色ゼリー" },
    [PM_SPOTTED_JELLY] = { 0, 0, "まだらゼリー" },
    [PM_OCHRE_JELLY] = { 0, 0, "黄土色ゼリー" },
    [PM_GRAY_OOZE] = { 0, 0, "灰色ウーズ" },
    [PM_BROWN_PUDDING] = { 0, 0, "茶色プリン" },
    [PM_GREEN_SLIME] = { 0, 0, "緑スライム" },
    [PM_BLACK_PUDDING] = { 0, 0, "黒プリン" },
    [PM_BARROW_WIGHT] = { 0, 0, "バロウ・ワイト" },
    [PM_NAZGUL] = { 0, 0, "ナズグル" },
    [PM_XORN] = { 0, 0, "ゾーン" },
    [PM_MONKEY] = { 0, 0, "猿" },
    [PM_APE] = { 0, 0, "類人猿" },
    [PM_OWLBEAR] = { 0, 0, "アウルベア" },
    [PM_YETI] = { 0, 0, "イエティ" },
    [PM_CARNIVOROUS_APE] = { 0, 0, "人喰い猿" },
    [PM_SASQUATCH] = { 0, 0, "サスカッチ" },
    [PM_SKELETON] = { 0, 0, "骸骨" },
    [PM_WRAITH] = { 0, 0, "レイス" },
    [PM_VAMPIRE_LEADER] = { 0, 0, "ヴァンパイアの長" },
    [PM_VAMPIRE] = { 0, 0, "吸血鬼" },
    [PM_BABY_GRAY_DRAGON] = { 0, 0, "灰色ドラゴンの子供" },
    [PM_BABY_GOLD_DRAGON] = { 0, 0, "金色ドラゴンの子供" },
    [PM_BABY_SILVER_DRAGON] = { 0, 0, "銀色ドラゴンの幼体" },
    [PM_BABY_RED_DRAGON] = { 0, 0, "赤色ドラゴンの子供" },
    [PM_BABY_WHITE_DRAGON] = { 0, 0, "白ドラゴンの子供" },
    [PM_BABY_ORANGE_DRAGON] = { 0, 0, "オレンジドラゴンの子供" },
    [PM_BABY_BLACK_DRAGON] = { 0, 0, "黒ドラゴンの子供" },
    [PM_BABY_BLUE_DRAGON] = { 0, 0, "青ドラゴンの子供" },
    [PM_BABY_GREEN_DRAGON] = { 0, 0, "緑ドラゴンの子供" },
    [PM_BABY_YELLOW_DRAGON] = { 0, 0, "黄色ドラゴンの子供" },
    [PM_GRAY_DRAGON] = { 0, 0, "灰色ドラゴン" },
    [PM_GOLD_DRAGON] = { 0, 0, "金色ドラゴン" },
    [PM_SILVER_DRAGON] = { 0, 0, "銀色ドラゴン" },
    [PM_RED_DRAGON] = { 0, 0, "赤色ドラゴン" },
    [PM_ORANGE_DRAGON] = { 0, 0, "オレンジドラゴン" },
    [PM_WHITE_DRAGON] = { 0, 0, "白ドラゴン" },
    [PM_BLACK_DRAGON] = { 0, 0, "黒ドラゴン" },
    [PM_BLUE_DRAGON] = { 0, 0, "青ドラゴン" },
    [PM_GREEN_DRAGON] = { 0, 0, "緑ドラゴン" },
    [PM_YELLOW_DRAGON] = { 0, 0, "黄色ドラゴン" },
    [PM_WHITE_UNICORN] = { 0, 0, "白ユニコーン" },
    [PM_GRAY_UNICORN] = { 0, 0, "灰色ユニコーン" },
    [PM_BLACK_UNICORN] = { 0, 0, "黒ユニコーン" },
    [PM_LONG_WORM] = { 0, 0, "ロングワーム" },
    [PM_JELLYFISH] = { 0, 0, "クラゲ" },
    [PM_PIRANHA] = { 0, 0, "ピラニア" },
    [PM_SHARK] = { 0, 0, "サメ" },
    [PM_GIANT_EEL] = { 0, 0, "巨大ウナギ" },
    [PM_ELECTRIC_EEL] = { 0, 0, "電気ウナギ" },
    [PM_KRAKEN] = { 0, 0, "クラーケン" },
    [PM_NEWT] = { 0, 0, "イモリ" },
    [PM_GECKO] = { 0, 0, "ヤモリ" },
    [PM_IGUANA] = { 0, 0, "イグアナ" },
    [PM_BABY_CROCODILE] = { 0, 0, "ワニの子供" },
    [PM_LIZARD] = { 0, 0, "トカゲ" },
    [PM_CHAMELEON] = { 0, 0, "カメレオン" },
    [PM_CROCODILE] = { 0, 0, "ワニ" },
    [PM_SALAMANDER] = { 0, 0, "サラマンダー" },
    [PM_LONG_WORM_TAIL] = { 0, 0, "ロングワームの尻尾" },
    [PM_STRAW_GOLEM] = { 0, 0, "藁のゴーレム" },
    [PM_FLESH_GOLEM] = { 0, 0, "肉のゴーレム" },
    [PM_CLAY_GOLEM] = { 0, 0, "土のゴーレム" },
    [PM_STONE_GOLEM] = { 0, 0, "岩のゴーレム" },
    [PM_WOOD_GOLEM] = { 0, 0, "木のゴーレム" },
    [PM_IRON_GOLEM] = { 0, 0, "鉄のゴーレム" },
    [PM_GLASS_GOLEM] = { 0, 0, "ガラスのゴーレム" },
    [PM_ROPE_GOLEM] = { 0, 0, "紐のゴーレム" },
    [PM_LEATHER_GOLEM] = { 0, 0, "皮のゴーレム" },
    [PM_GOLD_GOLEM] = { 0, 0, "金のゴーレム" },
    [PM_PAPER_GOLEM] = { 0, 0, "紙のゴーレム" },
    [PM_LORD_CARNARVON] = { 0, 0, "カーナボン卿" },
    [PM_PELIAS] = { 0, 0, "ペリアス" },
    [PM_SHAMAN_KARNOV] = { 0, 0, "呪術師カルノフ" },
    [PM_HIPPOCRATES] = { 0, 0, "ヒポクラテス" },
    [PM_KING_ARTHUR] = { 0, 0, "アーサー王" },
    [PM_GRAND_MASTER] = { 0, 0, "総師範" },
    [PM_ARCH_PRIEST] = { 0, 0, "主席司祭" },
    [PM_ORION] = { 0, 0, "勇者オリオン" },
    [PM_MASTER_OF_THIEVES] = { 0, 0, "盗賊の頭領" },
    [PM_LORD_SATO] = { 0, 0, "大名佐藤" },
    [PM_TWOFLOWER] = { 0, 0, "ツーフラワー" },
    [PM_NORN] = { 0, 0, "ノルン" },
    [PM_NEFERET_THE_GREEN] = { 0, 0, "緑のネフェレト" },
    [PM_MINION_OF_HUHETOTL] = { 0, 0, "フヘトトルの使い" },
    [PM_THOTH_AMON] = { 0, 0, "トート・アモン" },
    [PM_CHROMATIC_DRAGON] = { 0, 0, "クロマティック・ドラゴン" },
    [PM_CYCLOPS] = { 0, 0, "サイクロプス" },
    [PM_IXOTH] = { 0, 0, "イクソス" },
    [PM_MASTER_KAEN] = { 0, 0, "カエン" },
    [PM_NALZOK] = { 0, 0, "ナルゾク" },
    [PM_SCORPIUS] = { 0, 0, "大蠍" },
    [PM_MASTER_ASSASSIN] = { 0, 0, "暗殺者の頭領" },
    [PM_ASHIKAGA_TAKAUJI] = { 0, 0, "足利尊氏" },
    [PM_LORD_SURTUR] = { 0, 0, "支配者スルト" },
    [PM_DARK_ONE] = { 0, 0, "暗きもの" },
    /* 岩貫き類 */
    [PM_ROCK_PIERCER] = { 0, 0, "岩喰い" },
    [PM_IRON_PIERCER] = { 0, 0, "鉄喰い" },
    [PM_GLASS_PIERCER] = { 0, 0, "ガラス喰い" },
    /* 大型四足動物 */
    [PM_ROTHE] = { 0, 0, "ロゼ" },
    [PM_MUMAK] = { 0, 0, "ムーマク" },
    [PM_LEOCROTTA] = { 0, 0, "レオクロッタ" },
    [PM_WUMPUS] = { 0, 0, "ワンパス" },
    [PM_TITANOTHERE] = { 0, 0, "チタノゼア" },
    [PM_BALUCHITHERIUM] = { 0, 0, "バルキテリウム" },
    [PM_MASTODON] = { 0, 0, "マストドン" },
    /* コボルドのアンデッド */
    [PM_KOBOLD_MUMMY] = { 0, 0, "コボルドのミイラ" },
    [PM_KOBOLD_ZOMBIE] = { 0, 0, "コボルドのゾンビ" },
    /* 3.7/5.0 で追加されたモンスター */
#ifdef PM_CERBERUS
    [PM_CERBERUS] = { 0, 0, "ケルベロス" },
#endif
#ifdef PM_BEHOLDER
    [PM_BEHOLDER] = { 0, 0, "ビホルダー" },
#endif
#ifdef PM_BABY_SHIMMERING_DRAGON
    [PM_BABY_SHIMMERING_DRAGON] = { 0, 0, "揺らめくドラゴンの子供" },
#endif
#ifdef PM_SHIMMERING_DRAGON
    [PM_SHIMMERING_DRAGON] = { 0, 0, "揺らめくドラゴン" },
#endif
#ifdef PM_VORPAL_JABBERWOCK
    [PM_VORPAL_JABBERWOCK] = { 0, 0, "ヴォーパル・ジャバウォック" },
#endif
#ifdef PM_VAMPIRE_MAGE
    [PM_VAMPIRE_MAGE] = { 0, 0, "吸血鬼の魔術師" },
#endif
#ifdef PM_CHARON
    [PM_CHARON] = { 0, 0, "カロン" },
#endif
#ifdef PM_EARENDIL
    [PM_EARENDIL] = { 0, 0, "エアレンディル" },
#endif
#ifdef PM_ELWING
    [PM_ELWING] = { 0, 0, "エルウィング" },
#endif
#ifdef PM_GOBLIN_KING
    [PM_GOBLIN_KING] = { 0, 0, "ゴブリンの王" },
#endif
#ifdef PM_HIGH_ELF
    [PM_HIGH_ELF] = { 0, 0, "ハイエルフ" },
#endif
};

static int
pmname_gender_slot(struct permonst *pm, int mgender)
{
    if ((mgender == MALE || mgender == FEMALE) && pm->pmnames[mgender])
        return mgender;
    return NEUTRAL;
}

const char *
jp_pmname(struct permonst *pm, int mgender)
{
    int pmidx, gslot;
    const char *jp;

    if (!pm)
        return "";

    gslot = pmname_gender_slot(pm, mgender);
    pmidx = (int) pm->pmidx;

    if (pmidx >= LOW_PM && pmidx < NUMMONS) {
        jp = mon_jp_names[pmidx][gslot];
        if (!jp && gslot != NEUTRAL)
            jp = mon_jp_names[pmidx][NEUTRAL];
        if (jp)
            return jp;
    }
    return pm->pmnames[gslot];
}

const char *
jp_pmname_from_idx(int pmidx, int mgender)
{
    if (pmidx >= LOW_PM && pmidx < NUMMONS)
        return jp_pmname(&mons[pmidx], mgender);
    return "";
}

